// Celestial art: Aurion's portrait (32x32), his hero power icon (24x24) and the
// Celestial cards (32x32). Referenced by HEROES.aurion and the c_* cards in cards.js.
// Preview at /sprites.html.

import { SKIN, CELESTIAL, OUTLINE } from './palettes.js';

const palette = [SKIN, CELESTIAL];

export default {
  // Aurion, Lord of the Stars: crowned in stars, silver hair, a night-sky mantle, rift-lit eyes.
  hero_celestial: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      .............................w..
      ................................
      ..w.......gg.ggOOgg.gg..........
      .........gggggGggGggggg.........
      ........WgGgGgGggGgGgGgW........
      .......wwwwwwwwwwwwwwwwwW.....c.
      .....WWwwwWwwwwCCwwwwWwwwWW.....
      .c..WwwwwWsssssccsssssWwwwwW....
      ...WwWwwWssssssssssssssWwwwwW...
      ....wwwwWsscwsssssswcssWwwW.....
      ...WwWwwWssssssssssssssWwwwW....
      W..WWWwwWSsssssSSsssssSWwwwwW...
      ..W..WwwWSssswwwwwwsssSWwwWwW...
      ....WWwwWWSsWwmmmmwWsSWWwwWWW...
      ...WWwwwwWWSWwswwswWSWWwwwwW....
      ...WwwwnwwWWSWwwwwWSWWwwnwwWW...
      ..WwwwnnwwwnngWwwWgnnwwwnnwwW...
      ..WWwnnnnwwnngWwwWgnnwwnnnnwWW..
      .WWwnnnnnnwnnngWWgnnnwnnnnnnwW..
      .nWwnWnnnnnnnnnggnnnnnnnncnnwWn.
      .nnnnnnnnnnnNnniinnNnnnnnnnnnnn.
      nnnwnnnnnnnNnniiiinnNnnnnnnnnnnn
      nnnnnnnnnnNnnnigginnnNnnnnnwnnnn
      nnnnnnnnnNnnnnigginnnnNnnnnnnnnn
      nnnnnnnwNnnnnnigginnnnnNnnnnnnnn
      nnnnnnnNnnnnniiggiinnnnnNnnnnnnn
      nnnnnnNnnnnnniiggiinnnnnwNnnnnnn
      nnWnnnNnnnnnnIiggiInnnnnnNnnnnnn
      nnnnnNnnnnnnnIiggiInnnnnnnNnnWnn
      nnnnnNnnnnnnnIiggiInnnnnnnNnnnnn
    `,
  },
  // Rift Grant Me Strength: a gauntleted fist wreathed in starlight.
  power_celestial: {
    palette,
    outline: OUTLINE,
    pixels: `
      ........................
      ...........O............
      ...........O............
      .....O....OwO......O....
      ......O.OOwwwOO...O.....
      .......OwwwwwwwO.O......
      ....OOOwwaaaaawwO.......
      .......waAaAaAaawOOO....
      ......OwaAaAaAaAawO.....
      .....O.waaaaaaaaaw.O....
      ....O..waaaaaaaaaw..O...
      ......OwAaaaaaaaAw......
      .......wAaaaaaaAawO.....
      .......wAgggggggAw......
      ........AGgGgGgGA.......
      ........iiiiiiiii.......
      ........iIiiiiiIi.......
      ........iIiiiiiIi.......
      ........iIiiiiiIi.......
      .......iiIiiiiiIii......
      .......iIIiiiiiIIi......
      ........................
      ........................
      ........................
    `,
  },
  // Chrono Acolyte: a hooded acolyte before a golden clock-ring, an hourglass in hand.
  card_c_acolyte: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ................g...............
      ............ggggggggg...........
      ..........gggg..O..gggg.........
      .........ggO.........Ogg........
      ........gg......G......gg.......
      .......gg......IG.......gg......
      .......gO.....IIi.......Og......
      ......gg.....IIIii.......gg.....
      ......gg....IIIdiii......gg.....
      ......g....IIIdddiii......g.....
      ......g...IIIdddddiii.....g.....
      .....ggO.IIIdddddddiii...Ogg....
      ......g..IIIddddddddiii...g.....
      ......g..IIIddcdddcdiii...g.....
      ......gg.IIIIddddddiiii..gg.....
      ......gg.IIIIddddddiiii..gg.....
      .......gIIIIIIiiiiiiiii.Og......
      .......gIIIIIIigggiiiiiigg......
      ........IIIIIIigggiiiiiig.......
      ........IIIIaaaaagiiiiii........
      ........IIIIIOOOggiiiiii........
      ........IIssIiOggssiiiii........
      ........IIssIOiOgssiiiii........
      ........IIssOOOOOssiiiii........
      ........IIIIaaaaagiiiiii........
      .......IIIIIIiigggiiiiii........
      .......IIIIIIiigggiiiiiii.......
      .......IIIIIiiigggiiiiiii.......
      .......IIIIIiiigggiiiiiii.......
      .......IIIIIiiigggiiiiiii.......
      ................................
    `,
  },
  // Cosmic Wraith: a ghost whose body is a slice of night sky.
  card_c_wraith: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      ................................
      ...............vv...............
      ..............vvvv..............
      .............vvvvvv.........W...
      ...W.......vvvvnnvvvv...........
      ..........vvvvnnnnvvvv..........
      .........vvvnnnnnnnnvvv.........
      ........vvvnnnnnnnnnnvvv........
      ........vvnnnnnnnnnnnnvv........
      ........vvnncccnnncccnvv........
      ........vvnncwcnnncwcnvv........
      .......vvvnncccnnncccnvv........
      .......vvvnnnnnnnnnnnnvv........
      .......vvvnwnnnnnnnnwnvvv.......
      ..V....vvvnnndnnnnnnnnvvv.......
      ...VVV.vvvnnnndddwnnnnvvv....V..
      ...VVVVvvvnnwnnnnnnnnnvvv..VV...
      ....VVVvvvnnnnnnnnnnnwvvv.VVV...
      ....VVVvvvnnnnnvvnnnvvvvvVVV....
      .....VVvvvvnnnwvvvnvvvvvVVVV....
      .....VVvvvvvnvvvvvvvvvvvVVVV....
      ......VVvvvvvvvvvv.vvvvVVVV.....
      ......VVvvv.vvvvv...vvvVVV......
      .......Vvv...vvvv....vV.........
      ........v....vvv................
      ..W...........vv................
      .............................W..
      ................................
      ..........................W.....
      ................................
    `,
  },
  // Unstable Nucleus: a crackling core inside three tilted orbits.
  card_c_nucleus: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      ................................
      ................................
      ........cccC.........C..........
      ........cwcCCC.....CCCCC........
      ........ccc...C...C....CC.......
      ........C......C.C......C.......
      ........C......CC.......O.......
      ........C.....CC.CC....OC.......
      ........C.....C...C.....C.......
      .........C.CCCPPPPPCCC.C........
      .......CCCC.CPPpppPPC.CCCC......
      .....CCC.C..PpppppppP..C.CCC....
      ....CC....CPPppOOOppPPC....CC...
      ...CC.....CPppOOwOOppPC.....ccc.
      ...C......CPppOwwwOppPC.....cwc.
      ...CC.....CPppOOwOOppPC.....ccc.
      ....CC....CPPppOOOppPPC....CC...
      .....CCC.C..PpppppppP..C.CCC....
      .......CCCC.CPPpppPPC.CCCC......
      ........OC.CCCPPPPPCCC.C........
      .......OC.....C...C.....C.......
      ........C.....CC.CC.....C.......
      ........C.......C.....O.C.......
      ........C......C.C.....OC.......
      ........ccc...C...C....CC.......
      ........cwcCCC.....CCCCC........
      ........cccC.........C..........
      ................................
      ................................
      ................................
    `,
  },
  // Starborn Seer: a stargazer with a brass telescope raised to a bright star.
  card_c_seer: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ............................c...
      ............................c...
      ...............W..........ccwcc.
      .......................GGGG.c...
      ....W..................GGGG.c...
      .......................GGGG.....
      .......................GGGG.....
      ......................Ggg.......
      .........p............Ggg.......
      .........vv..........Ggg........
      ........vv..........Ggg.........
      ......vvvv.........Ggg..........
      .....vvVVvv........Ggg..........
      ....vvVVVvvvv.....Ggg......W....
      ...vvVSSssssvv...Ggg............
      ....VVSSssssvv..Ggg.............
      ....VVSSsscsvv.Ggg..............
      ....VVSSssssvv.Ggg..W...........
      ....VVSSssssvvvgg...............
      ...VVVVVvvvvssvg................
      ...VVVVvvvvvvss..............W..
      ...VVVVvvvvvvvss................
      ...VVVVvvvvvvvv.................
      ...VVVVvvvvvvvv.................
      ...VVVVvvvvvvvv.........W.......
      ...VVVVvvvvvvvv.................
      ..VVVVVvvvvvvvvv................
      ..VVVVvvvvvvvvvv..W.............
      ..VVVVvvvvvvvvvv................
      ..VVVVvvvvvvvvvv................
      ................................
    `,
  },
  // Revenant: a dead knight's helm with rift-lit eyes and spectral flame.
  card_c_revenant: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      ................................
      ..............cc................
      ..............cc..cc............
      ..........cc..cc..cc............
      ..........cc..cc..cc..cc........
      ..........cc..cc..cc..cc........
      ..........cc..cc..cc..cc........
      ..........cc.cccccccc.cc........
      ........AAAAaaaaaaaaaaaac.......
      ........AAAAaaaaaaaaAaaac.......
      ........AAAAaaaaaaaaaAaa........
      ........AAAAaaaaaaaaaAaa........
      ........AAAAaaaaaaaaaaAa........
      ........Addddddddddddddd........
      .......AAddcwcdddddcwcdda.......
      .......AAddcccdddddcccdda.......
      .......AAddddddddddddddda.......
      .......AAAAaaaadddaaaaaaa.......
      .......AAAAaaAadddaAaaaaa.......
      .......AAAAaaaadddaaaaaaa.......
      .......AAAAaaAadddaAaaaaa.......
      ........AAAAaaadddaaaaaa........
      .........AAaAAadddaAaaa.........
      .........AAaAaadddaaaaa.........
      ..........AaaAaaaaaAaa..........
      ...........aaaaaaaaaa...........
      .....RRRRRRRRRRRRRRRRRRRRR......
      ....RRRRRRRRRRRRRRRRRRRRRRR.....
      ...RRRRRRRRRRRRRRRRRRRRRRRRR....
      ................................
    `,
  },
  // Comet Rider: an armoured lancer charging on a blazing comet.
  card_c_comet: {
    palette,
    outline: OUTLINE,
    pixels: `
      ..............WW.....W..........
      ...............AAaaaa...........
      ...............AAaaaa..........a
      ...W...........AAddcd........aa.
      ...............AAaaaa.......a.A.
      ...............AAaaaa.....aaAA..
      ..............IAAaaaa....a.A....
      ........W.....IIiiiii...aAA.....
      .............IIIiiiii.aaA.......
      ............CIIIiiii.aAA........
      ...........CCIIiisssaA..........
      ..........CCCIIiisssA...........
      ..........CCCIIiisss........W...
      ...........CCIIiiii.............
      ............CII..o..............
      .............oooooooo...........
      ...........oooooOOOooo..........
      .........oooooOOOOOOOoo.........
      .........ooooOOOOOOOOOoo........
      ........oooooOOOwwwOOOoo........
      .......oooooOOOwwwwwOOOo........
      .......oooooOOOwwwwwOOOoo.......
      ......ooooooOOOwwwwwOOOo........
      .....ooooooooOOOwwwOOOoo........
      .....ooooooooOOOOOOOOOoo........
      ....PPPPooooooOOOOOOOoo.........
      ...PPPPPPoooooooOOOooo..........
      ...PPPPPPPooooooooooo........W..
      ..PPPPPPPPoooooooo..............
      .PPPPPPPPooooooo................
      .oPPPPPPooo.............W.......
      PoPPPP..........................
    `,
  },
  // Skybridge Sentinel: a stone colossus with a constellation glowing in its chest.
  card_c_sentinel: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      ...........RRRrrrrrrrr..........
      ...........RRRrrrrrrrr..........
      ...........RRRrrrrrrrr..........
      ...........RRdcdddcdrr..........
      ...........RRdddddddrr..........
      ...........RRRrrrrrrrr..........
      ...........RRRrrrrrrrr..........
      ......RRRRrRRRrrrrrrrrrrrr......
      .RRrrrrRRRrrrrrrrrrrrrrrrrrrrrrr
      .RRrrrrRRRrrrrrrrrrrrrrrrrrrrrrr
      .RRrrrrRRRrrrrrrrrrrwrrrrrrrrrrr
      .RRrrrrRRrrwrrrrrrrCCrrrrrrrrrrr
      .RRrrrrRRrrrCCrrrCCrrCrrrrrrrrrr
      .RRrrrrRRrrrrrCrCrrrrCrrrrrrrrrr
      .RRrrrrRRrrrrrrwrrrrrCrrrrrrrrrr
      .RRrrrrRRrrrrrrrrrrrrrCrrrrrrrrr
      .RRrrrrRRrrrrrrrrrrrrCwrrrrrrrrr
      .RRrrrrRRrrrrrrrrrrCCrrrrrrrrrrr
      RRRRRRRRrrrrrrrrCCCrrrrrrrRRRRRR
      RRRRRRRRrrrrrrwCrrrrrrrrrrRRRRRR
      RRRRRRRRrrrrrrrrrrrrrrrrrrRRRRRR
      RRRRRRRRrrrrrrrrrrrrrrrrrrRRRRRR
      RRRRRRRrrrrrrr.....rrrrrrrRRRRRR
      .......rrrrrrr.....rrrrrrr......
      .......RRRRRRR.....RRRRRRR......
      .......RRRRRRR.....RRRRRRR......
      .......RRRRRRR.....RRRRRRR......
      cccccccccccccccccccccccccccccccc
      iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii
      iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii
    `,
  },
  // Event Horizon: a black disc ringed with frozen light.
  card_c_horizon: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................w...............
      ...............cwC..............
      ...............cwC..............
      ...........CCCCcwCCCCC..........
      .........CCCCCCcwCCCCCCC........
      .....wCCCCCCccccwccccCCCCccw....
      .....cwCCCccccc.w.cccccCCcwC....
      .....ccwCcccwwwwwwwwwccccwCC....
      .....CCcwcwwwwdddddwwwwcwCCC....
      ....CCCccwwwdddddddddwwwccCCC...
      ....CCccwwwdddddddddddwwwccCC...
      ...CCCccwwdddddddddddddwwccCCC..
      ...CCccwwdddddddddddddddwwccCC..
      ...CCccwwdddddddddddddddwwccCC..
      ...CCccwdddddddddddddddddwccCC..
      .CCCCc.wdddddddddddddddddw.ccccc
      wwwwwwwwdddddddddddddddddwwwwwww
      .ccccc.wdddddddddddddddddw.cCCCC
      ...CCccwdddddddddddddddddwccCC..
      ...CCccwwdddddddddddddddwwccCC..
      ...CCccwwdddddddddddddddwwccCC..
      ...CCCccwwdddddddddddddwwccCCC..
      ....CCccwwwdddddddddddwwwccCC...
      ....CCCccwwwdddddddddwwwccCCC...
      .....CCCwcwwwwdddddwwwwcwcCC....
      .....CCwccccwwwwwwwwwcccCwcc....
      .....CwcCCccccc.w.cccccCCCwc....
      .....wccCCCCccccwccccCCCCCCw....
      .........CCCCCCCwcCCCCCC........
      ...........CCCCCwcCCCC..........
      ...............Cwc..............
      ...............Cwc..............
    `,
  },
  // Starfire Bolt: a falling star, white-hot, with a fiery trail.
  card_c_starfire: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      ......................O.........
      ............W.........O.........
      ......................O.........
      .....W................O.........
      ..................wOOOOOOOw.....
      ..................OwOOOOOwO.....
      ..................OOwwOwwOO.....
      ..................OOwwOwwOO.....
      ..............OOOOOOOOwOOOOOOOO.
      ..................OOwwOwwOO.....
      ..................OOwwOwwOO.....
      ..................OwOOOOOwO.....
      ..................wOOOOOOOw.....
      .................OOOO.O.........
      ................OOOO..O.........
      ...............OOO....O.........
      ..............ooo.....O.........
      .............ooo.............W..
      ............ooo.................
      ...........oo...................
      ..........oo....................
      .........oo.....................
      ........PP......................
      .......P........................
      ......P.....................W...
      .....P..........................
      ....P...........................
      ................................
      ................................
      ................................
    `,
  },
  // Gravity Well: a violet spiral pulling rocks into its eye.
  card_c_gravity: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      ........V.V...V.VVVV............
      .......V....VV......VV.V........
      ......V...VV.....V......VV......
      .....V..VV...VVVV.VVVV....V.....
      ....ar..V..VV.........VV...V....
      ....rV.V..V...vvvvvvv...VV.ar...
      ...V..VV.V..vv.......vv...VVV...
      ...V..V.V..vv..vvvvv...VVVV..V..
      .....V.VV.vv.vvv...vvv..V..V..V.
      ..V..V.V.vv.vv..vvv...v..V.V..V.
      ..V.V..V.v..v.ppv.vvv..v..V.V..V
      ..V.V.V..v.v..p.O...vv.vv.V.V...
      ..V.V.v..v.v.pOOOOOp.vv.v.V..V.V
      ..V.V.v..v.v.pOwwwOpp.v.v..V.V.V
      ....V.v..v.v.OOwwwOOp.v..v.V.V..
      ..V.V.v..v.v..OwwwO.p.v..v.V.V..
      ..V.V..v.v..v.OOOOO.v.v..v.V.V..
      ..V..V.v..v..pppOp.vv.v.v..V.V..
      ...V.V..v.vv......vv.vv.v.V..V..
      ...V.VV.vv..vv...vv..v..v.V..V..
      ....V..V.vv...vvv...v..v..V.....
      ....V..VV.vvv.....vv..vvVV..V...
      .....V.VVV..vvvvvv...vv.VV..V...
      .....aV..VV.........v..V..Vr....
      .....rVVV..VVVVVVVVv..VV..rV....
      .........V...........V...V......
      ..........VVVV...VVVV...V.......
      .......VV.....VVV.....VV........
      .........VV........V.V..........
      ............VVV.VVV.............
    `,
  },
  // Oblivion: a black hole devouring a blazing accretion disc.
  card_c_oblivion: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      ....................W...........
      ................................
      ....W...........................
      ...........................W....
      ................................
      ................................
      ..............PPPPP.............
      ............PPdddddPP...........
      ...........PPdddddddPP..........
      ..........PPdddddddddPP.........
      ..........PdddddddddddP.........
      .......PPPdddddOOOdddddPPP......
      ....PPPPOPOOOOOoooooooOPOooPP...
      ...PPoOOOPodddddddddddoPoOOoPP..
      ..PPoOOooPdddddddddddddPooOOoPP.
      ..P.oOoo.PdddddddddddddP.ooOo.P.
      ..PPoOOoo.PdddddddddddP.ooOOoPP.
      ...PPoOOooPPdddddddddPPoOOooPP..
      ....PPooOOOPPdddddddPPOooPPPP...
      .......PPPooPPdddddPPPPPPP......
      ..............PPPPP.............
      ................................
      ................................
      ................................
      ................................
      ...W........................W...
      ................................
      ................................
      ................................
      ................................
    `,
  },
  // Glaive of the Rift: crescent blades either end, a rift crystal at its heart.
  card_c_glaive: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ......................AAAAA.....
      ....................AAaaaaaAA...
      ...................AaawwwwwaaA..
      ..................Aaaww...wwaaA.
      ..................Aaw.......wa..
      .................Aaww...........
      .................Aaw............
      .................Aaw....GG......
      .................Aaw...Gg.......
      .................Aaww.Gg........
      ..................AawGg.........
      ................c.AaGg..........
      ...................Gg...........
      ...............CCCGg............
      ..............CCcCC.............
      ............c.CcccC.c...........
      ..............CCcCC.............
      ..............GCCC..............
      .............Gg.................
      ............GaA.c...............
      ...........GwaA.................
      ..........GgwwaA................
      .........Gg..waA................
      ........Gg...waA................
      .............waA................
      ............wwaA................
      ...aw.......waA.................
      ..Aaaww...wwaaA.................
      ...AaawwwwwaaA..................
      ....AAaaaaaAA...................
      ......AAAAA.....................
    `,
  },
  // Lightshard Bow: a bow of light crystals with a shard-arrow nocked.
  card_c_bow: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      ................................
      ................................
      .........CCCW...................
      ........wwwwW...................
      .........cccW..............c....
      .........Cc.W...................
      ........Cc..W...................
      .....CCCc...W.......c...........
      ....wwwww...W...................
      .....ccc....W...................
      ......Cc....W...................
      .....Cc.....W...................
      .....Cc.....W...............c...
      ....CCC.....W..............ccc..
      ...wwwww....wwwwwwwwwwwwwwwwwwww
      ....ccc.....W..............CCC..
      .....Cc.....W...............C...
      .....Cc.....W...................
      ......Cc....W...................
      .....CCC....W...................
      ....wwwww...W...................
      .....cccc...W............c......
      ........Cc..W...................
      .........Cc.W.....c.............
      .........CCCW...................
      ........wwwwW...................
      .........cccW...................
      ................................
      ................................
      ................................
    `,
  },
};
