// Full-body hero figures for the main menu battle scene (src/menuscene.js).
// 32x32, facing right, feet on the bottom row; two poses per hero.
// Preview at /sprites.html.

import { SKIN, OUTLINE, WARLORD, VANGUARD, PYROMANCER, STALKER, ORACLE, SHADE } from './palettes.js';

export default {
  // Warlord: axe raised high, ready to leap.
  champ_warlord_windup: {
    palette: [SKIN, WARLORD],
    outline: OUTLINE,
    pixels: `
      ................................
      ...IIIIIwl...........w..........
      ...IIIIIlw..........w...........
      ...IIIIlllw.........w...........
      ...IIlllllwilllllliw............
      ...Ilillll.wiiiiiiw.............
      ...lilllll.iiiiiiii.............
      ...illllllcIIIIIIII.............
      .........cc.SSssks..............
      ..........ssSSssss..............
      ..........ssSbbbbmb.............
      ..........UUSbbbbbb.............
      .........uuuuBBBbbbuu...........
      .........uuuuBBBbbbuu...........
      .........UUUuuuuuuUUU...........
      .........UUURrccrrUUU...........
      ..........iRRrrrrrrr............
      ..........iRRrrrrrrr............
      ...........RRrrrrrrr............
      ...........RRrrrrrrr............
      ...........RRrrrrrrr............
      ..........CCCCCgCCCC............
      ..........CCCCCgCCCC............
      ............CCC.ccc.............
      ...........CCC...ccc............
      ...........CCC...ccc............
      ..........CCC.....ccc...........
      ..........CCC.....ccc...........
      .........CCC.......ccc..........
      ........kkkk.......CCCCC........
      ........kkkk.......CCCCC........
      ........kkkk.......kkkkk........
    `,
  },
  // Warlord: axe brought down in a crushing blow.
  champ_warlord_strike: {
    palette: [SKIN, WARLORD],
    outline: OUTLINE,
    pixels: `
      ................................
      ........w............w..........
      .........w..........w...........
      ..........w.........w...........
      ..........willlllliw............
      ...........wiiiiiiw.............
      ...........iiiiiiii.............
      ...........IIIIIIII.............
      ............SSssks..............
      ............SSssss..............
      ............Sbbbbmb.............
      ............Sbbbbbb.............
      .........uuuuBBBbbbuu...........
      .........uuuuBBBbbbuu...........
      .........UUUuuuuuuUUU...........
      .........UUURUUUrcUUU...........
      ..........iRRrrUUUrcuss.........
      ..........iRRrrrrssr.ssccil.....
      ...........RRrrrrssr....cIlll...
      ...........RRrrrrrrr....IIillll.
      ...........RRrrrrrrr....IIIllll.
      ..........CCCCCgCCCC....IIIilll.
      ..........CCCCCgCCCC....IIIIlll.
      ............CCC.ccc.....IIIIill.
      ...........CCC...ccc......IIIl..
      ...........CCC...ccc........Ii..
      ..........CCC.....ccc...........
      ..........CCC.....ccc...........
      .........CCC.......ccc..........
      ........kkkk.......CCCCC........
      ........kkkk.......CCCCC........
      ........kkkk.......kkkkk........
    `,
  },
  // Vanguard: shield braced, sword held back.
  champ_vanguard_guard: {
    palette: [SKIN, VANGUARD],
    outline: OUTLINE,
    pixels: `
      ..............bbb...............
      .............bbbbb..............
      .....l.......bbbbb..............
      ......l......BBBBB..............
      ......lI...lggggggg.............
      ......llI..iiiiiiii.............
      .......llI.iiiiiiii.............
      .......llIIiiiiiiii.............
      ........llIiiSssksI.............
      .........lliiSssssI.............
      ..........liiSsSssI.............
      ..........liiSssssI.............
      .........lliiIlllllgggggggg.....
      .........igiIIlllligttttttg.....
      .........iiIITttttigttgtttg.....
      ..........iiTTtgtttgttgtttg.....
      ..........iiTTgggttggtgtgtg.....
      ..........iiTTtgtttgttgtttg.....
      ...........iTTtgtttgttgtttg.....
      ...........iTTtgttt.gtgttg......
      ...........iTTtgttt.gtgttg......
      ...........iTTttttt.ggttgg......
      ...........iTTttttt..gttg.......
      ............TTttttt...gg........
      ...........III...iii..gg........
      ...........III...iii............
      ..........III....iii............
      ..........III....iii............
      .........III......iii...........
      ........kkkk......IIIII.........
      ........kkkk......IIIII.........
      ........kkkk......kkkkk.........
    `,
  },
  // Vanguard: sword thrust over the shield.
  champ_vanguard_thrust: {
    palette: [SKIN, VANGUARD],
    outline: OUTLINE,
    pixels: `
      ..............bbb...............
      .............bbbbb..............
      .............bbbbb..............
      .............BBBBB..............
      ...........lggggggg.............
      ...........iiiiiiii.............
      ...........iiiiiiii.............
      ...........iiiiiiii.............
      ...........iiSssksI.............
      ...........iiSssssI.............
      ...........iiSsSssI.............
      ...........iiSssssI..g...llllll.
      .........lliillllllllgllllllII..
      .........iiilllllliiIIlIIIII....
      .........iiiTTtttiiiIII.........
      ..........iiTTtgtgggggggg.......
      ..........iiTTggggttttttg.......
      ..........iiTTtgtgttgtttg.......
      ...........iTTtgtgttgtttg.......
      ...........iTTtgtggtgtgtg.......
      ...........iTTtgtgttgtttg.......
      ...........iTTtttgttgtttg.......
      ...........iTTttttgtgttg........
      ............TTttttggttgg........
      ...........III...iigttg.........
      ...........III...iigggg.........
      ..........III....iiigg..........
      ..........III....iii............
      .........III......iii...........
      ........kkkk......IIIII.........
      ........kkkk......IIIII.........
      ........kkkk......kkkkk.........
    `,
  },
  // Pyromancer: a fireball gathered overhead.
  champ_pyromancer_ready: {
    palette: [SKIN, PYROMANCER],
    outline: OUTLINE,
    pixels: `
      ..............O........f........
      .............rr......fffff......
      ............rrrr....ffoooff.....
      ...........rrrrrr...foOOOof.....
      ..........rrrrrrrr.ffoOyOoff....
      ..........RRrrrrrrr.foOOOof.....
      ..........RRfffffffrffoooff.....
      ..........RRoosssssr.fffff......
      ..........RRoosskssrrssf........
      ..........RRoosssss.rr..........
      ..........RRoosssssrr...........
      ..........RRoosssssr............
      ..........RRRRgggrrr............
      ...........RRRgggrr.............
      ..........RRRRggrrrr............
      ..........RRRRggrrrr............
      ..........RRRRggrrrr............
      ..........RRRrggrrrr............
      ..........RRRrggrrrr............
      .........ssRRrggrrrrr...........
      .........ssGGGGGGGGGG...........
      .........RRGGGGGGGGGG...........
      .........RRRRrggrrrrr...........
      .........RRRRrggrrrrr...........
      ........RRRRRrggrrrrrr..........
      ........RRRRRrggrrrrrr..........
      ........RRRRrrggrrrrrr..........
      ........RRRRrrggrrrrrr..........
      ........RRRRrrggrrrrrr..........
      .......RRRRRrrggrrrrrrr.........
      .......RRRRRrrggrrCCCCr.........
      ..............gg..CCCC..........
    `,
  },
  // Pyromancer: arm thrust out, flame leaving her palm.
  champ_pyromancer_throw: {
    palette: [SKIN, PYROMANCER],
    outline: OUTLINE,
    pixels: `
      ..............O.................
      .............rr.................
      ............rrrr................
      ...........rrrrrr...............
      ..........rrrrrrrr..............
      ..........RRrrrrrrr.............
      ..........RRfffffffr............
      ..........RRoosssssr............
      ..........RRoosskssr............
      ..........RRoosssss.............
      ..........RRoosssss.........f...
      ..........RRoosssss.......fffff.
      ..........RRRRgggrr.......foOof.
      ...........RRRgggrrrrrrrsffOOOff
      ..........RRRRggrrrr....ssfoOof.
      ..........RRRRggrrrr......fffff.
      .........RRRRRggrrrr........f...
      ........ssRRRrggrrrr............
      ........ssRRRrggrrrr............
      .........RRRRrggrrrrr...........
      .........RRGGGGGGGGGG...........
      .........RRGGGGGGGGGG...........
      .........RRRRrggrrrrr...........
      .........RRRRrggrrrrr...........
      ........RRRRRrggrrrrrr..........
      ........RRRRRrggrrrrrr..........
      ........RRRRrrggrrrrrr..........
      ........RRRRrrggrrrrrr..........
      ........RRRRrrggrrrrrr..........
      .......RRRRRrrggrrrrrrr.........
      .......RRRRRrrggrrCCCCr.........
      ..............gg..CCCC..........
    `,
  },
  // Stalker: bow drawn, arrow nocked.
  champ_stalker_draw: {
    palette: [SKIN, STALKER],
    outline: OUTLINE,
    pixels: `
      ................................
      ............vv..................
      ...........vvvvvv...............
      ...........vvvvvvvv.............
      ..........VVVvvvvvv.....x.......
      ..........VVVvvvvvv....xc.......
      ..........VVVVVVVVV..xx..c......
      ..........VVVssssss.x....cC.....
      .........xVVVssskssv......cC....
      .......zz.VVVssssssv......cC....
      .......cccVVVVVqqqqq......cC....
      .......cccVVVVVqqqqq......cC....
      .......cccVVVVVqqqqq.......cC...
      .......cccVcssCCCvvvvvvssCCCCCil
      .......cccVVssVvvvv....ss..cC...
      .......cccVVVcvxxvv.......cC....
      .......cccVVVvcvvxv.......cC....
      .......cccVVVvcvvvx.......cC....
      .......cccVVVvvcvvvx......cC....
      ..........VVVvvvcvv.x....cC.....
      ..........CCCCCCCcCC.xx..c......
      ..........CCCCCCCCcC...xc.......
      ..........VVV.C.c.c.....x.......
      ...........CCC...ccc............
      ..........C.C.....c.c...........
      ..........CCC.....ccc...........
      ..........C.C.....c.c...........
      .........CCC.......ccc..........
      ........C.C.........c.c.........
      .......kkkk.........CCCCC.......
      .......kkkk.........CCCCC.......
      .......kkkk.........kkkkk.......
    `,
  },
  // Stalker: the arrow loosed, string still humming.
  champ_stalker_loose: {
    palette: [SKIN, STALKER],
    outline: OUTLINE,
    pixels: `
      ................................
      ............vv..................
      ...........vvvvvv...............
      ...........vvvvvvvv.............
      ..........VVVvvvvvv.....x.......
      ..........VVVvvvvvv.....x.......
      ..........VVVVVVVVV.....xc......
      ..........VVVssssss.....xcC.....
      .........xVVVssskssv....x.cC....
      .......zz.VVVssssssv...x..cC....
      .......cccVVVVVqqqqq...x..cC....
      .......cccVVVVVqqqqq...x..cC....
      .......cccVVVVVqqqqq...x...cC...
      .......cccVcVvvvvvVVVVsss..cC...
      .......cccVVcVVVVVV...sss..cC...
      .......cccVVVcvvvvv....x..cC....
      .......cccVVVvcvvvv....x..cC....
      .......cccVVVvcvvvv....x..cC....
      .......cccVVVvvcvvv.....x.cC....
      ..........VVVvvvcvv.....xcC.....
      ..........CCCCCCCcCC....xc......
      ..........CCCCCCCCcC....x.......
      ..........VVV.C.c.c.....x.......
      ...........CCC...ccc............
      ..........C.C.....c.c...........
      ..........CCC.....ccc...........
      ..........C.C.....c.c...........
      .........CCC.......ccc..........
      ........C.C.........c.c.........
      .......kkkk.........CCCCC.......
      .......kkkk.........CCCCC.......
      .......kkkk.........kkkkk.......
    `,
  },
  // Oracle: standing calm with her staff.
  champ_oracle_idle: {
    palette: [SKIN, ORACLE],
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      ............AAA.AAA.............
      ...........Aww.....A............
      ..........Awwwwww...ggg.........
      .........AWWWwwwwwwggjgg........
      .........AWWWgggggggjjjg........
      .........AWWWSsssssggjgg........
      ..........WWWSskkss.ggg.........
      ..........WWWSssssswgG..........
      ..........WWWSssssswgG..........
      ..........WWWSssssswgG..........
      ..........WWWwwwwwwwgG..........
      ..........WWWwggwww.gG..........
      ...........WWWggwwwwgG..........
      ..........WWWWjgwwwwgG..........
      ..........WWWwggwwwssG..........
      ..........WWWwggwwwssG..........
      ..........WWwwggwwwwgG..........
      ..........ssGGGGGGGGgG..........
      ..........ssGGGGGGGGgG..........
      .........WWWwwggwwwwgG..........
      .........WWWwwggwwwwgG..........
      .........WWWwwggwwwwgG..........
      .........WWWwwggwwwwgG..........
      .........WWWwwggwwwwgG..........
      .........WWwwwggwwwwgG..........
      .........WWwwwggwwwwgG..........
      ........WWWwwwggwwwwgG..........
      ........WWWwwwggwwwwgG..........
      ........WWWwwwggwwwwgG..........
      ..............gg................
    `,
  },
  // Oracle: staff raised, light bursting from it.
  champ_oracle_cast: {
    palette: [SKIN, ORACLE],
    outline: OUTLINE,
    pixels: `
      .....................AAA........
      ....................AAaAA.......
      ............AAA.AAAAAaaaAA......
      ...........Aww.....AaaaaaA......
      ..........Awwwwww..AAaaaAA......
      .........AWWWwwwwww.AAaAA.......
      .........AWWWgggggg..AAA........
      ........AAWWWSsssss..gG.........
      .......AaAWWWSskkss.AgG.........
      ......AaaaWWWSssssswssG.........
      .......AaAWWWSssssswssG.........
      ........AsWWWSssssswwgG.........
      ..........WWWwwwwwww.gG.........
      ..........WWWwggwww..gG.........
      ...........WWWggwww..gG.........
      ..........WWWwjgwwww.gG.........
      ..........WWWwggwwww.gG.........
      ..........WWwwggwwww.gG.........
      ..........WWwwggwwww.gG.........
      ..........WGGGGGGGGG.gG.........
      ..........WGGGGGGGGG.gG.........
      .........WWWwwggwwww.gG.........
      .........WWWwwggwwwwwgG.........
      .........WWWwwggwwwwwgG.........
      .........WWWwwggwwwwwgG.........
      .........WWWwwggwwwwwgG.........
      .........WWwwwggwwwwwgG.........
      .........WWwwwggwwwwwgG.........
      ........WWWwwwggwwwwwgG.........
      ........WWWwwwggwwwwwgG.........
      ........WWWwwwggwwwwwgG.........
      ..............gg................
    `,
  },
  // Shade: a dagger raised to throw.
  champ_shade_stand: {
    palette: [SKIN, SHADE],
    outline: OUTLINE,
    pixels: `
      ................................
      .............v..................
      ............vqv.................
      ...........vvvqvv...............
      ...........vvvvvvv......dd......
      ..........vvvvvvvvv....ddD......
      ..........VVVvvvvvv...ddD.......
      ..........VVVNNNNNN..ddD........
      ..........VVVNNNNNN.ddD.........
      ..........VVVNNNxNxvgD..........
      ..........VVVNNNNNNvN...........
      ..........VVVNNNNNNvN...........
      ..........VVVvvvvvvv............
      .........VVVVvvvvvv.............
      .........Vvvvvvvvvv.............
      ........VVvvvvvvvvv.............
      ........VVvvvvvvvvv.............
      .......VVVvvvvvvvvv.............
      .......VVVVvvddvvvvv............
      ......VVVVVvvvDdddvv............
      ......VVVVVvvvvvDddd............
      ......VVVVVvvvvvvvvDd...........
      ......VVVVVvvvvvvvvv............
      ......VVVV..NNN.vvv.............
      ......V....NNN...vvv............
      ...........NNN...vvv............
      ..........NNN.....vvv...........
      ..........NNN.....vvv...........
      .........NNN.......vvv..........
      ........kkkk.......NNNNN........
      ........kkkk.......NNNNN........
      ........kkkk.......kkkkk........
    `,
  },
  // Shade: a low lunge, cloak streaming behind.
  champ_shade_dash: {
    palette: [SKIN, SHADE],
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      ................................
      ...............v................
      ..............vqv...............
      .............vvvqvv.............
      .............vvvvvvv............
      ............vvvvvvvvv...........
      ............VVVvvvvvv...........
      ............VVVNNNNNN...........
      ............VVVNNNNNN...........
      ............VVVNNNxNxv..........
      ............VVVNNNNNNv..........
      ...........VVVVNNNNNNv..........
      .........VVVVVVvvvvvvv..........
      .......VVVVVVVVvvvvvv...........
      ......VVVVVVvvvvvvvvvvgdd.......
      ....VVVVVVVVvvvvvvvvvNNdddddd...
      ...VVVVVVVVVvvvvvvvvvNNDDDDDdd..
      ..VVVVVVVVDDdvvvvvvv............
      ..VVVVVVDdddvvvvvvvv............
      ..VVVVVVdVVVvvvvvvvv............
      .VVVVVVVV...vvvvvvvv............
      .VVV........vvvvvvvv............
      ............NNN...vvv...........
      ...........NNN.....vvv..........
      .........NNNN.......v.v.........
      ........NNN.........vvv.........
      .......NNN...........vvv........
      .....kkkk.............NNNNN.....
      .....kkkk.............NNNNN.....
      .....kkkk.............kkkkk.....
    `,
  },
};
