// Hero portraits, 32x32. One sprite per class, referenced by CLASSES[*].portrait.
// Preview and check every sprite at /sprites.html.

import { SKIN, OUTLINE } from './palettes.js';

export default {
  // Ignatia the Kindled: hooded fire mage with flame hair and ember eyes.
  hero_pyromancer: {
    palette: [SKIN, { r: '#b3302b', R: '#7c1c23', p: '#4d1219', o: '#f28a26', O: '#ffd451', f: '#ff5f1f', y: '#ffc14a', g: '#e6b54a', G: '#a5741f' }],
    outline: OUTLINE,
    pixels: `
      ................................
      ...............OO...............
      ..............OooO..............
      ..............RrrR..............
      .............RrrrrR.............
      ............RrrrrrrR............
      ...........RrrrrrrrrR...........
      ..........RrrrrrrrrrrR..........
      .........RrrrrrrrrrrrrR.........
      ........RrrrRppppppRrrrR....o...
      .......RrrrRpffffffpRrrrR..O....
      .......RrrRpffOffOffpRrrR.......
      ......RrrRpffffffffffpRrrR......
      ....o.RrrRffssssssssffRrrR......
      ...O..RrrRfssssssssssfRrrR......
      .....RrrrRfsyyssssyysfRrrrR.....
      .....RrrrRfssssssssssfRrrrR.....
      .....RrrrRffsssSSsssffRrrrR.....
      ....RrrrrRfssssssssssfRrrrrR.O..
      ....RrrrrRffsssmmsssffRrrrrR....
      ..oRrrrrrrRfffssssfffRrrrrrrR...
      ...RrrrrrrrRffSSSSffRrrrrrrrR...
      ..RrrrrrrrrrRggggggRrrrrrrrrrR..
      ..RrrrrrrrrrgGgoogGgrrrrrrrrrR..
      .RrrrrrrrrrrgggRRgggrrrrrrrrrrR.
      .RrrrrrrrrrrrgRppRgrrrrrrrrrrrR.
      RrrrrrrrrrrrrrgGGgrrrrrrrrrrrrrR
      RrrrRrrrrrrrrrgGGgrrrrrrrrrRrrrR
      RrrRrrrrrrrrrrgGGgrrrrrrrrrrRrrR
      RrrRrrrrrrrrrrgGGgrrrrrrrrrrRrrR
      RrrRrrrrrrrrrrgGGgrrrrrrrrrrRrrR
      RrrRrrrrrrrrrrgGGgrrrrrrrrrrRrrR
    `,
  },
  // Brakka Ironjaw: horned iron helm, battle scar, braided beard, fur mantle.
  hero_warlord: {
    palette: [SKIN, { i: '#8f98a3', I: '#5b636e', l: '#c9d1d9', n: '#efe6d2', N: '#b7a98a', b: '#9a5528', B: '#5e2f17', u: '#7a5a3a', U: '#4f3a26', x: '#d33b2e' }],
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      ..n..........................n..
      ..nN........................Nn..
      ..nN........................Nn..
      ...nN.....llllllllllll.....Nn...
      ...nNN...liiiiiiiiiiiil...NNn...
      ....nNN.liiiiiiiiiiiiiil.NNn....
      .....nNNiiiiiiiiiiiiiiiiNNn.....
      ......NIiiiiiiiiiiiiiiiiIN......
      .......IiiIIIIIIIISIIIiiI.......
      .......IiIsssssssssxssIiI.......
      .......IiIsseesssseSssIiI.......
      .......IiIssssSssSssxsIiI.......
      .......IIBsssSSssSSsssBII.......
      ......BbbbbbbbbbbbbbbbbbbB......
      ......BbbbbBbmmmmmmbBbbbbB......
      ......BbbbbBBssbbssBBbbbbB......
      ......BBbbbBBBbbbbBBBbbbBB......
      .....uuBBbbbBBbbbbBBbbbBBuu.....
      ...uuuuuBBbbbbbbbbbbbbBBuuuuu...
      .uuuuuuuuBBbbbbbbbbbbBBuuuuuuuu.
      uuuUuuuuuuBBbbbBBbbbBBuuuuuuUuuu
      uuUuuuuuuuuBBbbbbbbBBuuuuuuuuUuu
      uUuuuuIIIIIuBBbbbbBBuIIIIIuuuuUu
      uuuuuIiiiiiIBBbBBbBBIiiiiiIuuuuu
      uuuuIiiiiiiiIBbbbbBIiiiiiiiIuuuu
      uuuIiiiiiiiiiIBbbBIiiiiiiiiiIuuu
      uuuIiiiiiiiiiiIBBIiiiiiiiiiiIuuu
      uuuIiiiiiiiiiiiIIiiiiiiiiiiiIuuu
      uuuIiiiiiiiiiiiiiiiiiiiiiiiiIuuu
      uuuIiiiiiiiiiiiiiiiiiiiiiiiiIuuu
    `,
  },
  // Wren Duskmantle: green hood and mask, arrows in a quiver over one shoulder.
  hero_stalker: {
    palette: [SKIN, { v: '#3f7a3a', V: '#26502a', q: '#6fa64a', c: '#6b4a2e', C: '#3d2a1c', x: '#e8e0c4', z: '#c23b2b', w: '#f5efe6' }],
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      ................................
      ..........VVVVVVVVVVVV..........
      ........VVvvvvvvvvvvvvVV........
      .......VvvvvvvvvvvvvvvvvV.......
      ......VvvvqqqqqqqqqqqqvvvV......
      ......VvvqqvvvvvvvvvvqqvvV......
      .....VvvqvvVVVVVVVVVVvvqvvV.....
      .....VvvvvVkkkkkkkkkkVvvvvV.....
      .....VvvvVkSSSSSSSSSSkVvvvV.....
      .....VvvvVkSssssssssSkVvvvV.....
      .....VvvvVSswessssewsSVvvvzx....
      .....VvvvVSssssssssssSVvvzx.....
      .....VvvvVVVVVVVVVVVVVVvzxc.....
      .....VvvvVVqqqVqqVqqqVVcvcV.....
      ....VvvvvVVqVVVVVVVVqVcvcvvV....
      ....VvvvvvVVqqqVVqqqVVvcvvvV....
      ...VvvvvvvvVVVVVVVVVVvvvvvvvV...
      ..VvvvvvvvvvVVVVVVVVvvvvvvvvvV..
      .VvvvvccvvvvvvVVVVvvvvvvvvvvvvV.
      VvvvvvCCccvvvvvVVvvvvvvvvvvvvvvV
      VvvvqvvvCCcvvvvVVvvvvvvvvvvqvvvV
      VvvqvvvvvvCccvvVVvvvvvvvvvvvqvvV
      VvvvvvvvvvvCCccVVvvvvvvvvvvvvvvV
      VvvvvvvvvvvvvCCcVvvvvvvvvvvvvvvV
      VvvvvvvvvvvvvvvCccvvvvvvvvvvvvvV
      VVvvvvvvvvvvvvvVCCccvvvvvvvvvvVV
      VvVvvvvvvvvvvvvVVvCCcvvvvvvvvVvV
      VvVvvvvvvvvvvvvVVvvvCccvvvvvvVvV
      VvVvvvvvvvvvvvvVVvvvvCCcvvvvvVvV
      VvVvvvvvvvvvvvvVVvvvvvvCcvvvvVvV
    `,
  },
  // Sister Lumen: veiled priestess under a golden halo, eyes closed in prayer.
  hero_oracle: {
    palette: [SKIN, { w: '#f2ede1', W: '#c9c1ae', g: '#e6b54a', G: '#a5741f', a: '#fff1b8', A: '#f5c84a', j: '#5ec8e8' }],
    outline: OUTLINE,
    pixels: `
      ................................
      ..........aAAAAAAAAAAa..........
      ........aAA..........AAa........
      .......aA..............Aa.......
      ......aA....WWWWWWWW....Aa......
      .....aA...WWwwwwwwwwWW...Aa.....
      .....A...WwwwwwwwwwwwwW...A.....
      ....aA..WwwwwwwwwwwwwwwW..Aa....
      ....A..WwwwGgggjjgggGwwwW..A....
      ....A..WwwSssssssssssSwwW..A....
      ....A..WwwSssssssssssSwwW..A....
      ....A..WwwSseAksskAesSwwW..A....
      ....A..WwwSssssssssssSwwW..A....
      ....aA.WwwSssssSSssssSwwW.Aa....
      .....A.WwwwSssssssssSwwwW.A.....
      .....aAWwwwSsssmmsssSwwwWAa.....
      ......AWwwwwSssssssSwwwwWA......
      .......WwwwwwSssssSwwwwwW.......
      .......WWWwwwwwHHwwwwwWWW.......
      .......wwwWwwwwWWwwwwWwww.......
      ......wwwwwWwgGggGgwWwwwww......
      .....wwwwwwwgGgaagGgwwwwwww.....
      .....wwwwwwwgGggggGgwwwwwww.....
      ....wwwwwwwwWgGggGgWwwwwwwww....
      ....wwwwwwwwwWggggWwwwwwwwww....
      ...wwwwwwwwwwWggggWwwwwwwwwww...
      ...wwwwwwwwwwwWggWwwwwwwwwwww...
      ...wwwwwwwwwwwWggWwwwwwwwwwww...
      ...wwwwwwwwwwwWggWwwwwwwwwwww...
      ...wwwwwwwwwwwWggWwwwwwwwwwww...
      ...wwwwwwwwwwwWggWwwwwwwwwwww...
      ...wwwwwwwwwwwWggWwwwwwwwwwww...
    `,
  },
  // Commander Hale: plumed knight helm, plate armour, crusader tabard.
  hero_vanguard: {
    palette: [SKIN, { i: '#a7b0bb', I: '#6b7480', l: '#e3e8ee', g: '#e6b54a', G: '#a5741f', b: '#4a7ee0', B: '#24479a', t: '#2f56a8', T: '#1f3b78' }],
    outline: OUTLINE,
    pixels: `
      .............bbbbbb.............
      ............bBbbbbBb............
      ...........bBbbBBbbBb...........
      ............BbbbbbbB............
      ..........gggggggggggg..........
      .........liiiiiiiiiiiil.........
      ........liiiiiiiiiiiiiil........
      .......liiiiiiiiiiiiiiiil.......
      .......liIIIIIIIIIIIIIIil.......
      .......lIggggggggggggggIl.......
      .......liIssssssssssssIil.......
      .......liIseesssssseesIil.......
      .......liIssssssssssssIil.......
      .......liIsssssSSsssssIil.......
      .......liIssskkkkkksssIil.......
      ........kkssskmmmmkssskk........
      ........kkssskskkskssskk........
      ........kkksssskksssskkk........
      ........kkkksssssssskkkk........
      ......gggggIssssssssIggggg......
      ....lliiiiigIIIIIIIIgiiiiill....
      ..lliiiiiiiigllllllgiiiiiiiill..
      .liiiiiiiiiiigTttTgiiiiiiiiiiil.
      liiiIiiiiiiiigttttgiiiiiiiiIiiil
      liiIiiiiiiiiiigttgiiiiiiiiiiIiil
      iiiIiiiiiiIIIgttttgIIIiiiiiiIiii
      iiiIiiiiiIIttttggttttIIiiiiiIiii
      IiiIiiiiiItttttggtttttIiiiiiIiiI
      IiiIiiiiiIttggggggggttIiiiiiIiiI
      IiiIiiiiiItttttggtttttIiiiiiIiiI
      IiiIiiiiiItttttggtttttIiiiiiIiiI
      IiiIiiiiiItttttggtttttIiiiiiIiiI
    `,
  },
  // Vex the Unseen: a face lost in shadow but for two violet eyes; dagger at the ready.
  hero_shade: {
    palette: [SKIN, { v: '#4a2f6b', V: '#2e1c45', q: '#6d4a9a', n: '#140c1c', x: '#c58cff', X: '#f4e2ff', d: '#d5dbe2', D: '#7d8794', h: '#6b4a2e', g: '#c9a54a', G: '#8a6c2a' }],
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      ...........VVVVVVVVVV...........
      .........VVvvvvvvvvvvVV.........
      ........VvvvvvvvvvvvvvvV........
      .......VvvvqqqqqqqqqqvvvV.......
      ......VvvvqvvvvvvvvvvqvvvV......
      ......VvvqvvvvvvvvvvvvqvvV......
      .....VvvqvVVVVVVVVVVVVvqvvV.....
      .....VvvvVnnnnnnnnnnnnVvvvV.....
      .....VvvvVnnnnnnnnnnnnVvvvV.....
      .....VvvvVnnnnnnnnnnnnVvvvV...d.
      .....VvvvVnnXxnnnnxXnnVvvvV..d..
      .....VvvvVnnnxnnnnxnnnVvvvV.dD..
      .....VvvvVnnnnnnnnnnnnVvvvVdD...
      .....VvvvVVnnnnnnnnnnVVvvvDD....
      ....VvvvvvVVVVVVVVVVVVvgvgvV....
      ....VvvvvvvVVVVVVVVVVvvvhvvV....
      ...VvvvvvvvvVVVVVVVVvvvhvgvvV...
      ..VvvvvvvvvvvVVVVVVvvvhvvvvvvV..
      .VvvvvvvvvvvvvVggVvvvgvvvvvvvvV.
      VvvvvvvvvvvvvvvGGvvvvvvvvvvvvvvV
      VvvvvvvvvvvvvvvVVvvvvvvvvvvvvvvV
      VvvvvvvvvvvvvvvVVvvvvvvvvvvvvvvV
      VvvvvvvvvvvvvvvVVvvvvvvvvvvvvvvV
      VVvvvvvvvvvvvvvVVvvvvvvvvvvvvvVV
      VvVvvvvvvvvvvvvVVvvvvvvvvvvvvVvV
      VvVvvvvvvvvvvvvVVvvvvvvvvvvvvVvV
      VvVvvvvvvvvvvvvVVvvvvvvvvvvvvVvV
      VvVvvvvvvvvvvvvVVvvvvvvvvvvvvVvV
      VvVvvvvvvvvvvvvVVvvvvvvvvvvvvVvV
      VvVvvvvvvvvvvvvVVvvvvvvvvvvvvVvV
    `,
  },
};
