// Game mode emblems for the title screen, 32x32. Referenced by `icon:` in src/modes.js.
// Preview at /sprites.html.

import { NEUTRAL, CELESTIAL, OUTLINE } from './palettes.js';

export default {
  // Enter the Rift: two swords crossed over a tear in the Rift.
  mode_standard: {
    palette: NEUTRAL,
    outline: OUTLINE,
    pixels: `
      ................................
      ..............PpxpP.............
      ..............PpxpP.............
      ...............PpxpP............
      ......l........PpxpP......l.....
      .......ll.......PpxpP...ll......
      .......ill......PpxpP..lli......
      ........ill....PpxpP..lli.......
      ........iill...PpxpP.llii.......
      .........iill.PpxpP.llii........
      ..........illlPpxpPllli.........
      ...........illpxpP.lli..........
      ............illpxplli...........
      .............illxlli............
      ..............illliP............
      ...............illpP............
      ..............llillpP...........
      .............lliiill............
      ............lliipiill...........
      ...........lliipxpiill..........
      ...........lliPpxpPill..........
      .....yY...lliPpxpP..ill...Yy....
      ......yY.lli.PpxpP...ill.Yy.....
      .......yYli...PpxpP...ilYy......
      ........ybb...PpxpP...Ybb.......
      ........bbyY...PpxpP.Yy.bb......
      .......bb..yY..PpxpPYy...bb.....
      .......bb...y..PpxpPy....bb.....
      ......bb.......PpxpP......bb....
      ...yyyb.......PpxpP........yyy..
      ...yyy........PpxpP........yyy..
      ...yyy........PpxpP........yyy..
    `,
  },
  // Challenge the Riftkin: eyes watching from inside the Rift, under five stars (the five Riftkin).
  mode_riftkin: {
    palette: CELESTIAL,
    outline: OUTLINE,
    pixels: `
      ...............cc...............
      ........c.....cwwc.....c........
      ........c......cc......c........
      ......ccwcc..........ccwcc......
      ........c..............c........
      ........c....VVVVVV....c........
      ...........VVvvvvvvVV...........
      ...c......VVvIIIIIIvVV......c...
      ..cwc.....VvIddddddIvV.....cwc..
      ...c.....VpIddddddddIpV.....c...
      ........VVvIddddddddIvVV........
      ........VvIddddddddddIvV........
      ........VvIddddddddddIvV........
      .......VvIIddddddddddIIvV.......
      .......VvIddddddddddddIvV.......
      .......VvIdoOddddddOodIvV.......
      .......VvIdddOoddoOdddIvV.......
      .......VvIddddddddddddIvV.......
      .......VvIddddddddddddIvV.......
      .......VvIddddddddddddIvV.......
      .......VvIddddddddddddIvV.......
      .......VvIIddddddddddIIvV.......
      ........VpIddddddddddIpV........
      ........VvIddddddddddIvV........
      ........VVvIddddddddIvVV........
      .........VvIddddddddIvV.........
      ..........VvIddddddIvV..........
      ..........VVvIIIIIIvVV..........
      ...........VVpvvvvpVV...........
      .............VVVVVV.............
      ................................
      ................................
    `,
  },
};
