// Game mode emblems for the title screen, 32x32. Referenced by `icon:` in src/modes.js.
// Preview at /sprites.html.

import { NEUTRAL, OUTLINE } from './palettes.js';

export default {
  // Enter the Rift: two swords crossed over a tear in the Rift.
  mode_standard: {
    palette: NEUTRAL,
    outline: OUTLINE,
    pixels: `
      ................................
      ..............PpxpP.............
      ..............PpxpP.............
      ...............PpxpP............
      ......l........PpxpP......l.....
      .......ll.......PpxpP...ll......
      .......ill......PpxpP..lli......
      ........ill....PpxpP..lli.......
      ........iill...PpxpP.llii.......
      .........iill.PpxpP.llii........
      ..........illlPpxpPllli.........
      ...........illpxpP.lli..........
      ............illpxplli...........
      .............illxlli............
      ..............illliP............
      ...............illpP............
      ..............llillpP...........
      .............lliiill............
      ............lliipiill...........
      ...........lliipxpiill..........
      ...........lliPpxpPill..........
      .....yY...lliPpxpP..ill...Yy....
      ......yY.lli.PpxpP...ill.Yy.....
      .......yYli...PpxpP...ilYy......
      ........ybb...PpxpP...Ybb.......
      ........bbyY...PpxpP.Yy.bb......
      .......bb..yY..PpxpPYy...bb.....
      .......bb...y..PpxpPy....bb.....
      ......bb.......PpxpP......bb....
      ...yyyb.......PpxpP........yyy..
      ...yyy........PpxpP........yyy..
      ...yyy........PpxpP........yyy..
    `,
  },
};
