// Oracle card art, 32x32. Referenced by `sprite:` in cards.js.
// Preview at /sprites.html.

import { SKIN, ORACLE, OUTLINE } from './palettes.js';

const palette = [SKIN, ORACLE];

export default {
  // Ward of Light: a raised palm inside a ring of runes.
  card_o_ward: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ...........AAAAAAAAAA...........
      .........AAAAAAgAAAAAAA.........
      ........AAA..........AAA........
      ......AAAAg..........gAAAA......
      ......AA....aaaaaaaa....AA......
      .....AA...aaa......aaa...AA.....
      ....AAA..aa...H.H.H..aa..AAA....
      ....AAg.aa..H.s.s.s...aa.gAA....
      ...AA...a...s.s.s.s....a...AA...
      ...AA..aa...s.s.s.s....aa..AA...
      ...AA..a....s.s.s.s.....a..AA...
      ...AA..a....sssssss.....a..AA...
      ...AA..a....sssssss.H...a..AA...
      ...Ag..a....sssssss.s...a..gA...
      ...AA..a....ssssssssS...a..AA...
      ...AA..a....sssssssS....a..AA...
      ...AA..aa...ssssssS....aa..AA...
      ...AA...a....sssssS....a...AA...
      ....AAg.aa...sssssS...aa.gAA....
      ....AAA..aa...sssS...aa..AAA....
      .....AA...aaa.wwww.aaa...AA.....
      ......AA....awwwwwwa....AA......
      ......AAAAg..wwwwwwW.gAAAA......
      ........AAA.wwwwwwwW.AAA........
      .........AAAwwwwwwwWAAA.........
      ...........AwwwwwwwWA...........
      ............wwwwwwwW............
      ............wwwwwwwW............
      ............wwwwwwwW............
      ............wwwwwwwW............
      ................................
    `,
  },
  // Candle Keeper: a hooded monk bearing a candle.
  card_o_candle: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      ................................
      ............nnnnnnnn............
      ..........nnnnnnnnnnnn..........
      .........nnnnnnnnnnnnnn.........
      ........nnnNNNNNNNNNNnnn........
      .......nnnNSssssssssSNnnn.......
      .......nnnNSsessssesSNnnn.......
      .......nnnNSssssssssSNnnn.......
      .......nnnNSsssSSsssSNnnn.......
      .......nnnnNSssssssSNnnnn.......
      ......nnnnnNNSnGGnSNNnnnnn......
      .....nnnnnnnNGGOAGGNnnnnnnn.....
      ....nnnnnnnnnGAOOAGnnnnnnnnn....
      ...nnnnnnnnnGAaoOaAGnnnnnnnnn...
      ...nnnnNnnnnGAaaaaAGnnnnNnnnn...
      ..nnnnnNnnnnnGAaaAGnnnnnNnnnnn..
      ..nnnnnNnnnnnGGAAGGnnnnnNnnnnn..
      ..nnnnNnnnnnnnncWnnnnnnnnNnnnn..
      ..nnnnNnnnnnnnncWnnnnnnnnNnnnn..
      ..nnnnNnnnnnnnncWnnnnnnnnNnnnn..
      ..nnnnNnnnnnnnncWnnnnnnnnNnnnn..
      ..nnnnNnnnnnnnncWnnnnnnnnNnnnn..
      ..nnnnNnnnnnnnncWnnnnnnnnNnnnn..
      ..nnnnNnnnnnssscWsssnnnnnNnnnn..
      ..nnnnNnnnnnssscWsssnnnnnNnnnn..
      ..nnnnNnnnnnggggggggnnnnnNnnnn..
      ..nnnnNnnnnnGGGGGGGGnnnnnNnnnn..
      ..nnnnNnnnnnnnnnnnnnnnnnnNnnnn..
      ..nnnnNnnnnnnnnnnnnnnnnnnNnnnn..
      ..nnnnNnnnnnnnnnnnnnnnnnnNnnnn..
    `,
  },
  // Humbling Light: a cone of light from the clouds.
  card_o_humbling: {
    palette,
    outline: OUTLINE,
    pixels: `
      ....WwwwwwW.WwwwwwwW.WwwwwwW....
      .WWWWwwwwwW.WwwwwwwW.WwwwwwWWWW.
      WwwwWwwwwwwWWwwwwwwWWwwwwwwWwwwW
      WwwwWwwwwwW..WwwwwW..WwwwwwWwwwW
      WwwwWwwwwwW..WWWWWW..WwwwwwWwwwW
      .WWW.WWwWW....awwA....WWwWW.WWW.
      .......W.....AawwA......W.......
      .............AawwA..............
      .............AawwA..............
      ............AAawwAA.............
      ............AaawwaA.......A.....
      ............AaawwaA.......A.....
      .....A.....AAaawwaAA....AAwAA...
      .....A.....AAaawwaAA......A.....
      ...AAwAA...AAaawwaAA......A.....
      .....A....AAaaawwaaAA...........
      .....A....AAaaawwaaAA...........
      ..........AAaaawwaaAA...........
      .........AAAaaawwaaAAA..........
      .........AAAaaawwaaAAA..........
      .........AAaaaawwaaaAA..A.......
      .......AAAAaaaawwaaaAAAAwA......
      ......AwAAAaaaawwaaaAAA.A.......
      .......AAAAaaaawwaaaAAA.........
      .......AAAAAAAAAAAAAAAAA........
      .....AAAAAAAAAAAAAAAAAAAAAA.....
      ....AAAAAaaaaaaaaaaaaaaAAAAA....
      ...AAAAAaaaaaaaaaaaaaaaaAAAAA...
      ....AAAAAaaaaaaaaaaaaaaAAAAA....
      .....AAAAAAAAAAAAAAAAAAAAAA.....
      .........AAAAAAAAAAAAAA.........
      ................................
    `,
  },
  // Thought Theft: a mind giving up its secrets.
  card_o_theft: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      ....................gggggggggg..
      ..v.......VVVV......gaaaaaaaag..
      .......VVVVVVVVV....gwwwwwwwwg..
      ......VVVVVVVVVVV...gwwvvvwwwg..
      .....VVVVVVvVVVVVV..gwwwwwvwwg..
      ....VVVVvvvvvvvVVVvvgvwwwvwwwg..
      ....VVVvvvvavvvvVVv.gwwwvwwwwg..
      ....VVVvvaaaaavvvvV.gwwwwwwwwg..
      ....VVVvvaaaaavvVVV.gwwwvwwwwg..
      ...VVVvvaaaaaaavvVV.gwwwwwwwwg..
      ...VVVVvvaaaaaveeVV.gwwwwwwwwg..
      ...VVVVvvaaaaavvVVV.gwwwwwwwwg..
      ...VVVVvvvvavvvvVVVVgggggggggg..
      ...VVVVVvvvvvvvVVVVVV...........
      ...VVVVVVVVvVVVVVVVV............
      ...VVVVVVVVVVVVVVVV...........v.
      ....VVVVVVVVVVVVVVV.............
      ....VVVVVVVVVVVVVVV.....v.......
      ....VVVVVVVVVVVVVV..............
      ....VVVVVVVVVVVVV...............
      ....VVVVVVVVVVVV............v...
      ....VVVVVVVVVVVV................
      ....VVVVVVVV....................
      ....VVVVVVVV....................
      ....VVVVVVVV....................
      ....VVVVVVVV....................
      ....VVVVVVVV....................
      ....VVVVVVVV....................
      ....VVVVVVVV....................
      ....VVVVVVVV....................
    `,
  },
  // Hymnal Guardian: a winged stone sentinel with an open hymnal.
  card_o_hymnal: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ............A......A............
      ............uuuuuuuu............
      .uu.......uuqAAqqAAquu......uu..
      .uuu.....uqqqqqqqqqqqqu....uuu..
      uuuuu...uqqqqqqqqqqqqqqu..uuuuu.
      uuuqu...uqqQuuuuuuuuQqqu..uuuuu.
      uuuquu..uqQuuuuuuuuuuQqu.uuuuuu.
      uuuquu..uqQuQQuuuuQQuQqu.uuuuuu.
      uuuquuu.uqQuuuuuuuuuuQquuuuuuuu.
      .uuuqquuuqQuuuuQQuuuuQquuuuuuu..
      .uuuqquuuqqQuuuuuuuuQqquuuuuuu..
      .uuuqquuqqqqQQQQQQQQqqqquuuuuu..
      .uuuqquqqqqqqqqqqqqqqqqqquuuuu..
      .uuuquqqqqqqqqqqqqqqqqqqqquuuu..
      ..uuuqqqqqqqqqqqqqqqqqqqqqquu...
      ..uuqqqqqqqqqqqqqqqqqqqqqqqqu...
      ..uqqqqqqqqqqqqqqqqqqqqqqqqqqu..
      ..uqqqqqGwwwwwwGGwwwwwwGqqqqqu..
      ..uqqqqqGwwwwwwGGwwwwwwGqqqqqu..
      ..uqqqqqGwWWWWWGGWWWWWwGqqqqqu..
      ..uqqqqqGwwwwwwGGwwwwwwGqqqqqu..
      ..uqqquuuwWWWWWGGWWWWWwuuuqqqu..
      ..uqqquuuwwwwwwGGwwwwwwuuuqqqu..
      ..uqqquuuwWWWWWGGWWWWWwuuuqqqu..
      ..uqqquuuwwwwwwGGwwwwwwuuuqqqu..
      ..uqqqqqGGGGGGGGGGGGGGGGqqqqqu..
      ..uqqqqqqQqqqqqqqqqqqqQqqqqqqu..
      ..uqqqqqqQqqqqqqqqqqqqQqqqqqqu..
      ..uqqqqqqQqqqqqqqqqqqqQqqqqqqu..
      ..uqqqqqqQqqqqqqqqqqqqQqqqqqqu..
      ..uqqqqqqQqqqqqqqqqqqqQqqqqqqu..
    `,
  },
  // Final Judgment: a golden sword descending from the heavens.
  card_o_judgment: {
    palette,
    outline: OUTLINE,
    pixels: `
      ....WWwwwwwWwwwwwwwWWwwwwwWW....
      ..W.WwwwwwwWwwwwwwwWwwwwwwwW.W..
      WwwwWwwwwwwWwwgggGwWwwwwwwwWwwwW
      wwwwwwwwwwwWWwgggGwWwwwwwwwwwwww
      wwwwwWwwwwwWWWgggGWWWwwwwwWwwwww
      wwwwwWWwwwWW.WgggGW.WWwwwWWwwwww
      WwwwW.WWWWW...gjjG...WWWWW.WwwwW
      ..W......gggggjjjjggggg......W..
      .........GGGGGjjjjGGGGG.........
      .............wwjjII.............
      .............wwaaII.............
      .............wwaaII......a......
      ......a......wwaaII......a......
      ......a......wwaaII....aawaa....
      ....aawaa....wwaaII......a......
      ......a......wwaaII......a......
      ......a......wwaaII.............
      .............wwaaII.............
      .............wwaaII.............
      ....a........wwaaII........a....
      ...awa.......wwaaII.......awa...
      ....a........wwaaII........a....
      .............wwaaII.............
      ........a....wwaaII.............
      .......awa...wwaaII....a........
      ........a....wwwIII...awa.......
      .............wwwIII....a........
      ..............wwII..............
      ..............wwII..............
      ...............wI...............
      ...............wI...............
      ................................
    `,
  },
  // Radiant Nova: an eight-pointed burst of holy light.
  card_o_nova: {
    palette,
    outline: OUTLINE,
    pixels: `
      ...............A................
      ...............A................
      ...............A................
      ...............A................
      ...............A................
      ..............AAA...............
      ..............AAA...............
      ..............aaa...............
      ........A.....aaa......A........
      .........A....aaa.....A.........
      ..........A..aAAAA...A..........
      ...........AAAaaaaAAA...........
      ...........AAaaaaaaAA...........
      ..........aAaaawwaaaA...........
      .....AAaaaAaaawwwwaaaAaaAA......
      AAAAAAAaaaAaawwwwwwaaAaaAAAAAAA.
      .....AAaaaAaawwwwwwaaAaaAA......
      ..........AaaawwwwaaaA..........
      ...........AaaawwaaaA...........
      ...........AAaaaaaaAA...........
      ...........AAAaaaaAAA...........
      ..........A...AAAA...A..........
      .........A....aaa.....A.........
      ........A.....aaa......A........
      ..............AAA...............
      ..............AAA...............
      ...............A................
      ...............A................
      ...............A................
      ...............A................
      ...............A................
      ................................
    `,
  },
  // Divine Seraph: a four-winged angel beneath a halo.
  card_o_seraph: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      .ww........AAAAAAAAAA.......ww..
      wwww......A..........A.....wwww.
      wwWw.......AAAAAAAAAA......wwww.
      wwwWw.......gggggggg......wwwww.
      wwwwWw.....gggggggggg....wwwwww.
      wwwwWW....ggssssssssgg...wwwww..
      .wwwwWW...ggsessssesgg..wwwwww..
      .wwwwWW...ggssssssssgg..wwwwww..
      .wwwwwWWW.ggsssmmsssgg.wwwwwww..
      .wwwwwWWW..ggssssssgg..wwwwwww..
      ..wwwwwWWW..gssssssg..wwwwwww...
      ..wwwwwWWwwwwwwwwwwwwwwwwwwww...
      ...wwwwwwwwwwwggggwwwwwwwwww....
      ...wwwwwwwwwwwgAAgwwwwwwwwww....
      ....w..wwwwwwwwggwwwwwwwwww.....
      .......wwwwWwwwwwwwwWwwww.......
      .......wwwwWwwwwwwwwWwwww.......
      ........wwwWwwwwwwwwWwww........
      .......wwwwWwwwwwwwwWwww........
      .....wwwwwwWwwwwwwwwWwwwww......
      ....wwwwwwwWwwwwwwwwWwwwwww.....
      ...wwwwwwwwWwwwwwwwwWwwwwwww....
      ..wwwwWwwwwWwwwwwwwwWwwwwwwww...
      ..wwwwWwwwwWwwwwwwwwWwwwwwwww...
      ..wwWWWwwwwWwwwwwwwwWwwwwwwww...
      .wwwWwwwwwwWwwwwwwwwWwwwwwwwww..
      .wWwWwwwwwwWwwwwwwwwWwwwwwwwww..
      .wWwwwwwwwwWwwwwwwwwWwwwwwwwwwW.
      wwwwwwwwwwwWwwwwwwwwWwwwwwwwwww.
      ..ww.wwwwwwWwwwwwwwwWwwwwwwww...
      .....wwwwwwWwwwwwwwwWwwwwww.....
    `,
  },
};
