// Hero power icons, 24x24, drawn in each class's palette. Referenced by
// CLASSES[*].heroPower.sprite in cards.js. Preview at /sprites.html.

import { SKIN, OUTLINE, PYROMANCER, WARLORD, STALKER, ORACLE, VANGUARD, SHADE } from './palettes.js';

export default {
  // Spark: a crackling four-point spark.
  power_pyromancer: {
    palette: [SKIN, PYROMANCER],
    outline: OUTLINE,
    pixels: `
      ........................
      ...........o............
      ...........o............
      ...........o............
      ...........o.......o....
      ...o.......o............
      ...........O............
      .......o...O....o.......
      ........o.Off..o........
      .........ffOOff.........
      ........OfOyyOf.........
      .oooooOOfOyyyyOfOooooo..
      ........fOyyyyOf........
      .........fOyyOf.........
      .........ffOOff.........
      ........o..ff..o........
      .......o...O....o.......
      ...........o............
      ...........o........o...
      ....o......o............
      ...........o............
      ...........o............
      ........................
      ........................
    `,
  },
  // Brace: a riveted iron shield with a red band.
  power_warlord: {
    palette: [SKIN, WARLORD],
    outline: OUTLINE,
    pixels: `
      ........................
      ........................
      ........................
      ...IIIIIIIIIIIIIIIIII...
      ...IIiiliiirriiiiiiII...
      ...IIgiliiirriiiiigII...
      ...IIiiliiirriiiiiiII...
      ...IIiiliiirriiiiiiII...
      ...IIiiliiirriiiiiiII...
      ...IIrrlrrrrrrrrrrrII...
      ...IIiiliiirriiiiiiII...
      ...IIiiliiirriiiiiiII...
      ...IIgiliiirriiiiigII...
      ....IiiliiirriiiiiiI....
      .....IiliiirriiiiiI.....
      ......IliiirriiiiI......
      .......IiiirriiiI.......
      ........IiirriiI........
      ........IIirriII........
      .........IIrrII.........
      ...........gI...........
      ........................
      ........................
      ........................
    `,
  },
  // Volley: three arrows raining in.
  power_stalker: {
    palette: [SKIN, STALKER],
    outline: OUTLINE,
    pixels: `
      ...........z............
      ..........cz............
      ........zzzz............
      ............c...........
      .......z.....c..........
      ......z.......c.........
      .....zz........c........
      ....z..c........c.......
      ..z.....c........c......
      ..z......c........cl....
      .cz.......c.......iilll.
      zzz........c.......iill.
      ...c........c......iiil.
      ....c........c.....iiii.
      .....c........illl......
      ......c.......iill......
      .......c......iiil......
      ........c.....iiiil.....
      .........cl......ii.....
      .........iilll..........
      ..........iill..........
      ..........iiil..........
      ..........iiii..........
      ........................
    `,
  },
  // Mend: a radiant healing cross.
  power_oracle: {
    palette: [SKIN, ORACLE],
    outline: OUTLINE,
    pixels: `
      ........................
      ........................
      ........AAAAAAAA........
      ...w..AAAAAAAAAAAA......
      .....AA..AaaaaA..AA.w...
      ....AA...AaaaaA...AA....
      ...AA....AawwaA....AA...
      ...A.....AawwaA.....A...
      ..AA.....AawwaA.....AA..
      ..AAAAAAAAawwaAAAAAAAA..
      ..AAaaaaaaawwaaaaaaaAA..
      ..AAaawwwwwwwwwwwwaaAA..
      ..AAaawwwwwwwwwwwwaaAA..
      ..AAaaaaaaawwaaaaaaaAA..
      ..AAAAAAAAawwaAAAAAAAA..
      ..AA.....AawwaA.....AA..
      ...A.....AawwaA.....A...
      ...AA....AawwaA....AA...
      ....AA...AaaaaA...AA....
      .....AA..AaaaaA..AAw....
      ....w.AAAAAAAAAAAA......
      ........AAAAAAAA........
      ........................
      ........................
    `,
  },
  // Muster: a plumed recruit's helmet, called to arms.
  power_vanguard: {
    palette: [SKIN, VANGUARD],
    outline: OUTLINE,
    pixels: `
      ........................
      ........................
      ........................
      ........................
      ..................yy....
      ..........bb......yy....
      .........bBbb...yyyyyy..
      ..........bBbb..yyyyyy..
      ...........bb.....yy....
      ..................yy....
      ........................
      .........IIIIII.........
      .......llliggiiII.......
      ......IllliggiiiII......
      ......liiiiggiiiiI......
      .....IiiiiiggiiiiiI.....
      .....IiiiiiggiiiiiI.....
      .....iiiiiiggiiiiii.....
      .gggggggggggggggggggggg.
      .iiiiiiiiiiiiiiiiiiiiii.
      .IIIIIIIIIIIIIIIIIIIIII.
      ........................
      ........................
      ........................
    `,
  },
  // Blade Kit: a shadow-wreathed dagger.
  power_shade: {
    palette: [SKIN, SHADE],
    outline: OUTLINE,
    pixels: `
      ........................
      ........................
      ........................
      ....................d...
      ............VVVVV.Dd....
      ...........VVVVVDDdX....
      ..........VVvvvDDdXX....
      ..x......VVvvvDDdXXV....
      .........VVvvDDdXXXV....
      ......VVVVVvDDdXXXVV....
      ....VVVVVVVDDDXXXvVV....
      ...VVVvvvVDDDXXXvvVV....
      ...VVvvvvDDDdXXvvVV.....
      ..VVvvvvDDDdXXVVVVx.....
      ..VVvvvDDDdXXVVVV.......
      ..VVvvDDDdXXvVV.........
      ..VgvvDDdXXvvVV.........
      ..VVgDDdXXvvvVV.........
      ...VVgdXXvvvVV..........
      ...VVcgvvvvVVV..........
      ....cCVgVVVVV........x..
      ...cC.VVgVV.............
      ..cC....................
      .g......................
    `,
  },
};
