// Pyromancer card art, 32x32. Referenced by `sprite:` in cards.js.
// Preview at /sprites.html.

import { SKIN, PYROMANCER, OUTLINE } from './palettes.js';

const palette = [SKIN, PYROMANCER];

export default {
  // Cinder Bolt: a fireball streaking down with a burning tail.
  card_p_cinderbolt: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      .............................Ff.
      ............................f.F.
      ..........................FFoO..
      ......................O..FooF...
      ..................O....FfffoF...
      ......................FffFfF....
      ....................FfffFff.....
      ..................FFffFfffF.....
      .................FFfFFfFfF.O....
      ...............FFFFFffFff.......
      ......O.......FFFFFfFfFfF.......
      ............FFFFFfFFfFfF........
      ..........FFFFFFfFFFFFFF........
      ........FFFFFFFFFfFfFFF.O.......
      .......FfffffffFFFfFFF..........
      ......FfffooofffFFFFFF..........
      .....FffoooooooffFFFF...........
      .....FffooOOOooffFFF............
      .....FfooOOyOOoofFFF............
      ....FFfooOyyyOoofFF.............
      .....FfooOOyOOoofFF.............
      .....FffooOOOooffF..............
      .....FffoooooooffF..............
      ......FfffooofffF...............
      .......FfffffffF................
      ........FFFFFFF.................
      ....O......F....................
      ................................
      ................................
      ................................
      ................................
    `,
  },
  // Rime Lance: a crystal ice spear in flight.
  card_p_rimelance: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      ................................
      ............a..............zza..
      ...........aza..........zzzzaA..
      ............a..........zzzzaAA..
      ......................zzzzaAA...
      ......................zzzaAAA...
      ...a..................zzaAAAA...
      ..aza.............a..zzaAAAA....
      ...a.............aza.zaAAAA.....
      ..................a..aAA........
      ....................Aa..........
      ...................Aa........a..
      ......a...........Aa........aza.
      .....aza.........Aa..........a..
      ......a.........Aa..............
      ...............Aa...............
      ..............Aa................
      .............Aa.......a.........
      ............Aa.......aza........
      .........aaAa.........a.........
      ........aaAD....................
      .......aaADD....................
      .......aADD...a.................
      .......ADD...aza................
      ......Aa......a.................
      .....Aa.........................
      ....Aa..........................
      ...Aa...........................
      ................................
      ................................
    `,
  },
  // Spark Shower: three sparks raining down.
  card_p_sparkshower: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      ................................
      ....................O.....F.....
      .........................FFF....
      ........................FfF.....
      ....O.................FFfF......
      .....................FFfF.......
      ....................FFfFF.......
      .................FFFFfFF........
      ................FfffFFF.....O...
      ...............FfoOofF..........
      ...............FfOyOfF..........
      ...............FfoOofF..........
      ...O..........FFFfffF...........
      .............FfF.FFF............
      ...........FFfF.................
      ..........FFfF..................
      .........FFfFF..................
      ......FFFFfFF..................f
      .....FfffFFF.................Ff.
      ....FfoOofF................FFfF.
      ....FfOyOfF.............FFFFfF..
      ....FfoOofF............FfffFFF..
      .....FfffF............FfoOofF...
      ......FFF.............FfOyOfF...
      ......................FfoOofF...
      ............O..........FfffF....
      ........................FFF.....
      ................................
      .............................O..
      ................................
    `,
  },
  // Runeweaver Apprentice: a young mage reading a glowing rune book.
  card_p_runeweaver: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      ................................
      ................................
      ................................
      ...........................p....
      ............hhhhhhhh............
      ..........hhhhhhhhhhhh..........
      ....p....hhhhhhhhhhhhhh.........
      .........hhhchhhhhhchhh.........
      ........hhhhshhsshhshhhh..p.....
      ........hhsssssssssssshh........
      .....p..hhseesssssseeshh........
      ........hhsssssssssssshh........
      ........hhsssssSSssssshh........
      .........hssssmmmmssssh.........
      ..........SSssssssssSS...p......
      ......p.....SSssssSS............
      ..........rrrrrrrrrrrr..........
      ........rrrrrrggggrrrrrr........
      ......rrrrprrRggggRrrrprrr......
      ....rrrrrrrrprggPgrprrrrrrrr....
      ...rrrrrrrrrRPgPggPRrrrrrrrrr...
      ..rrrrrCwwwwwwwCCwwwwwwwCrrrrr..
      ..rrrrrCwwwwwwwCCwwwwwwwCrrrrr..
      ..rrrrrCwwppwpwCCwpwpwwwCrrrrr..
      ..rrrrrCwwwwpwwCCwwpwwwwCrrrrr..
      ..rrrrsswwpwwwwCCwwpwpwwssrrrr..
      ..rrrrssWWWWWWWWWWWWWWWWssrrrr..
      ..rrrrssWWWWWWWWWWWWWWWWssrrrr..
      ..rrrrrCCCCCCCCCCCCCCCCCCrrrrr..
      ..rrrrrrrrRrrrggggrrrRrrrrrrrr..
    `,
  },
  // Glacial Breath: a great snowflake in a cold gust.
  card_p_glacial: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      .............AA.AAA.............
      ..........A.A......A..A....a....
      ...a...AA..............AA.aza...
      ..aza.A.................A..a....
      ...a..A.........................
      ...............a..........AA....
      ...AA........a....a.........A...
      ...A..........aa.a..........A...
      ..A............aa...............
      .......a..a....z.....a..a....A..
      ........a.a..........aaa........
      .........aa.....z....az.........
      .......aaa.z.......zz.aaa.......
      ............zzaaaaz...........a.
      ..............azza...........aza
      ..............azza............a.
      .............zaaaaz.............
      .......aaazzz...z..zzzaaa.......
      .........za..........az.........
      .......aaaa.....z....aaaa.......
      ..........a..........a....a.....
      ......a........aa........aa.....
      ..............a..a.......a......
      .......a.....a..a.a.....a.......
      ........aa............a.........
      ..........a.....a....aa.....a...
      ....a.......aaa..a.aa......aza..
      ...aza..........a...........a...
      ....a...........................
      ................................
      ................................
    `,
  },
  // Ashfall: an erupting volcano under ash clouds.
  card_p_ashfall: {
    palette,
    outline: OUTLINE,
    pixels: `
      ..............QQQ...............
      .............QQqQQ....QQQ.......
      .......QQQ...QqqqQ...QQQQQ......
      ......QQqQQ..QqqqQ..QQqqqQQ.....
      .....QQqqqQQoQQqQQooQqqqqqQ.....
      .....QqqqqqQooQQQOooQqqqqqQ.....
      .....QQqqqQQfoOOOOofQQqqqQQ.....
      ...QQQQQqQQ..oOOOOoffQQQQQ.QQQ..
      ..QqqqQQQQ...ooOOooff.QQQ.QqqqQ.
      ..QqqqQ......foOOoff.o....QqqqQ.
      ..QqqqQ......foOOo........QqqqQ.
      ...QQQ.....offoOO..........QQQ..
      .............ffOO...............
      ...............OOf.........o....
      ............fOOOOOOf............
      .....o.....uffffffffQ...........
      ..........uouqqoqqQoQQ..........
      ..........ufuqqfqqQfQQ..........
      .........uuufqqfqqfQQQQ.........
      ........uuuqfqqfqqqfQQQQ........
      .......uuoqoqqqoqqqoqQQQQo......
      .......uuufqqqqfqqqqfQQQQ.......
      ...o..uuuqfqqqqfqqqqfqQQQQ......
      .....uuuqqfqqqqfqqqqqfqQQQQ.....
      ....uuuqqqoqqqqoqqqqoqqqQQQQ.o..
      ....uuuqqqfqqqqfqqqqfqqqQQQQ....
      ...uuuqqqqfqqqqfqqqqfqqqqQQQQ...
      ..uuuqqqqfqqqqqfqqqqqqfqqqQQQQ..
      .uuuqqqqoqqqqqqoqqqqqqoqqqqQQQQ.
      .uuuqqqqfqqqqqqfqqqqqqfqqqqQQQQ.
      uuuqqqqqqfqqqqqfqqqqqfqqqqqqQQQQ
      uuqqqqqqqqqqqqqqqqqqqqqqqqqqqQQQ
    `,
  },
  // Ember Colossus: a molten rock giant crowned in flame.
  card_p_embercolossus: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ..............O..O..............
      ............f.OffO.f............
      ...........ffOyOOyOff...........
      ...........fOOyyyyOOf...........
      ..........FffOOOOOOffF..........
      ..........qqqqqqqqqqqq..........
      .........quqqqqqqqqqquq.........
      .........uqqqqqqqqqqqqu.........
      .........qqOOqqqqqqOOqq.........
      .........qqyOqqqqqqOyqq.........
      .........QqqqqqqqqqqqqQ.........
      ....qqqq.QQqffffffffqQQ.qqqq....
      ..qquuqqqQQqqqqqqqqqqQQqqquuqq..
      .quufqqqqqQqqqqqqqqqqQqqqqquuuq.
      quuqqfqqqqqqqqqqqqqqqqqqqqqfquuq
      quqqqfqqqqqqqqOOOOqqqqqqqqfqqquq
      qqqqqqOqqqqqqOyyyyOqqqqqqqfqqqqq
      qqqqqqfqqqqqqOyyyyOqqqqqqOqqqqqq
      qqqQqfqqqqqqqqOOOOqqqqqqqqfqQqqq
      qqQqqOqqqqqqqqqqqqqqqqqqqqfqqQqq
      QqQqqqfqqqqqfqqqqqqqqqqqqqfqqQqQ
      QqQqqqqfqqqqfqqqqqqqfqqqqqqOqQqQ
      QqQqqqqqOqqfqqqqqqqqfqqqqqfqqQqQ
      QqQqqqqqfqfqqqqqqqqqqfqqqfqqqQqQ
      QqQqqqqqfqOqqqqqqqqqqqfqOqqqqQqQ
      QqQqqqqfqqqfqqqqqqqqqqOqfqqqqQqQ
      QqQqqqqOqqqfqqqqqqqqqqfqqfqqqQqQ
      QqQqqqqqfqqqfqqqqqqqqfqqqqfqqQqQ
      QqQqqqqqfqqqqqqqqqqqfqqqqqfqqQqQ
      QqQqqqqqfqqqqqqqqqqqfqqqqqqqqQqQ
      QqQqqqqqqfqqqqqqqqqqqqqqqqqqqQqQ
    `,
  },
  // Starfall Meteor: a stone meteor trailing violet starfire.
  card_p_starfall: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      ..............................a.
      .....a......................pp..
      .....a.....................pPp..
      ...aazaa.....a...........PpPp...
      .....a......aza.........PPap....
      .....a.......a........PPPaPP....
      .....................PPPpPP.....
      ...................PPPPpPP......
      ..................PPPppPPP......
      ................PPPPpPpPP.......
      ...............PPPPpPpPP........
      .............PPPPPpPpPPP....a...
      ............PPPPpPPpPPP....aza..
      ....O....QQQQQPpPPPPPP......a...
      ....O..QQQqqqQQQpPpPPP..........
      ......OQqqqqqqqQQpPPP...........
      ......QqqqqqqqqqQPPP............
      .....ooqquqqqqqqQQPP............
      .....OoqqqQqqqqqqQP.............
      .....OOqqqqqqQqqqQ..............
      .....OOquqqqqqqqqQ........a.....
      .....OOqqqqquqqqQQ........a.....
      ......OOqqqqqqqqQ.......aazaa...
      ......OOOqqqqqqQQ.........a.....
      .....O.OOOOOooQQ..........a.....
      .........OOOOo..................
      ..............O.....a...........
      ...a...............aza..........
      ..aza...............a...........
      ...a............................
    `,
  },
};
