// The Riftkin: the five Celestial bosses' portraits (32x32), Nightlord Grun's hero
// power icon (24x24) and the Rift Demon it summons (32x32). Referenced by the
// boss heroes in HEROES (cards.js). Preview at /sprites.html.

import { SKIN, CELESTIAL, OUTLINE } from './palettes.js';

const palette = [SKIN, CELESTIAL];

export default {
  // Zarth the Colossus: a block of living stone with a heavy brow, a vast square jaw and great shoulders rising behind it, the Rift glowing through its cracks and mouth, a crown of drifting boulders.
  hero_zarth: {
    palette,
    outline: OUTLINE,
    pixels: `
      ....R.......r......r.......R....
      ...RrR...c.rrr....rrr.....RrR...
      ....R.......r......r..w....R....
      ...........RrrR..RrrR...........
      ..........RRRRRRRRRRRR..........
      .........RrrrrrAArrrrrR.........
      ........RrrrrrrAArrrrrrR........
      ........RrrrrrCAACrrrrrR........
      ........RAAAAAcAAcAAAAAR........
      ....R..RRRRRRRcRRcRRRRRRR..R.W..
      ...RrR.RddddddRrrRddddddR.RrR...
      ..RrrRRRdccdddRrrRdddccdRRRrrR..
      .RcrrRRrRddddRrrrrRddddRrRRrrrR.
      .RrrRRrrrRRRRrrrrrrRRRRrrrRRrrR.
      RrrrRRArrrrrrRrrrrRrrrrrrARRrrrR
      RrrdRrArrrrrRRrrrrRRrrrrrArRdrrR
      RrrdRrrrrrrrRrrrrrrRrrrrrrrRdrrR
      RrrdRrrrrrrrrrrrrrrrrrrrrrrRdrrR
      RrrdRrrrrRRRRRRRRRRRRRRrrrrRdrrR
      RrrdRrrrRdccccccccccccdRrrrRdrrR
      RrrdRrrrrRRRRRRRRRRRRRRrrrrRdrrR
      RrrdRArrrrrrrrrrrrrrrrrrrrARdrrR
      RrrdRArrrrrrrrrrrrrrrrrrrrARdrrR
      RrrdRArrrrAAAAAAAAAAAArrrrARdrrR
      RrrdRArrrArrrrrRRrrrrrArrrARdrrR
      RrrdRRrrrArrrrrRRrrrrrArrrRRdrrR
      RrrdRRRRRRRRRRRRRRRRRRRRRRRRdrrR
      RrrddddddddddddddddddddddddddrrR
      rrrrrrrrrddddddddddddddrrrrrrrrr
      rrrrrrrrrrRddddddddddRrrrrrrrrrr
      rrrrcrrrrrrRddddddddRrrrrrrcrrrr
      rrrcrrrrrrrrRddddddRrrrrrrrrcrrr
    `,
  },
  // Void Serpent Gal'kun: a cobra of the void, nebula-marked hood, star-slit eyes, fangs and a forked tongue.
  hero_galkun: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      ............VnnnnnnVV...........
      ...W......VVnnnnnnnnVV..........
      .........VVnnnnnnnnnnVV.....W...
      ........VVnnnnnnnnnnnnVV........
      .......VVnnIIIiiiiiinnnVV.......
      .......VVnnIIIiiiiiinnnVV.......
      ......VVnnnIIviiiiiinnnnVV......
      .....VVnnnnIIIiiiivinnnnnVV.....
      ....VVnnnnIIIIiviiiinnnnnnVV....
      ...VVnnnnnIIOdOiiOdOinnnnnnVV...
      ...VVnnnPnIIOdOiiOdOinnPnnnVV...
      ..VVnnnPpPIIIIiviiiiinPpPnnnVV..
      ..VVnnPpppIIIviiiiiiiPpppPnnVV..
      .VVnnnnPpPIIIiiiiiviinPpPnnnnVV.
      .VVnnnnnPnIIIiiviiiinnnPnnnnnVV.
      .VVnnnnnnnnIIviiiiiinnnnnnnnnVV.
      .VVnnnnnnPnIIiiiiivinnPnnnnnnVV.
      .VVnnnnnPpPIIiiviiinnPpPnnnnnVV.
      .VVnnnnPpppPIviiiiinPpppPnnnnVV.
      ..VVnnnnPpPnIiiiiivnnPpPnnnnVV..
      ..VVnnnnnPnnIddddddnnnPnnnnnVV..
      ...VVnnnnnnnnddddddnnnnnnnnVV...
      ...VVnnnnnnnnwnppnwnnnnnnnnVV...
      ....VVnnnnnnnwnppnwnnnnnnnVV....
      ..W.VVnnnnnnnnnppnnnnnnnnnVV....
      .....VVnnnnnnnnppnnnnnnnnVV..W..
      .....VVnnnnnnnpnnpnnnnnnnVV.....
      ......VVnnVVnnnnnnnnVVnnVV......
      ..........VVnnnpnnnnVV..........
      ..........VVnnnnnnnnVV..........
    `,
  },
  // Ylva, Starlight Priestess: a crescent-moon circlet, silver-blue hair, eyes closed in prayer, a starlit violet robe.
  hero_ylva: {
    palette,
    outline: OUTLINE,
    pixels: `
      ..............aaa...............
      .............aa.................
      .............aw.................
      .............aw.................
      ....w........aaccc..............
      ..............aaaaa.............
      .......WWCCCccccccccCCCWW.......
      ......WWcccCCCCCCCCCCcccWW.w....
      ......WccCsssssSSsssssCccW......
      .....WWcCssssssssssssssCcWW.....
      .....WccCssssssssssssssCccW.....
      .....WccCsSkkksssskkkSsCccW.....
      .....WccCssssssssssssssCccW.....
      .....WccCSssssSssSssssSCccW.....
      .....WccCSssssssssssssSCccW.....
      ..c.WWccCCSssssmmssssSCCccWW....
      ....WcccCCCSssssssssSCCCcccW....
      ...WWccCCvvCSSSSSSSSCvvCCccWW...
      ...WccCvvvvvvvcCCcvvvvvvvCccWW..
      ..WWcCvvvvvvvvcwwcvvvvvvvvCcWW..
      ..WccvvvvvvvvOvCCvOvvvvvvvvccW..
      .WWcvvvvVvvvvvvvvvvvvvvVvvvvcWW.
      .WccvvvvvVvvvvvvvvvvvvVvvvvvccW.
      .WcvvvvvvvVvvvvvvvvvvVvvvvvvvcW.
      WWvvwvvvvvvVvvvvvvvvVvvvvvvwvvWW
      WcvvvvvvvvvVvvvwwvvvVvvvvvvvvvcW
      WvvvvvvvvvvvVvvvvvvVvvvvvvvvvvvW
      vvvvvvvwvvvvVvvvvvvVvvvvwvvvvvvv
      vvvvvvvvvvvvVvvvvvvVvvvvvvvvvvvv
      vvwvvvvvvvvvvVvvvvVvvvvvvvvvvwvv
      vvvvvvvvvvvvvVvvvvVvvvvvvvvvvvvv
      vvvvvvvvvvvvvVvvvvVvvvvvvvvvvvvv
    `,
  },
  // Manus Darkhammer: a heavy dark-iron war-helm with a forge-gold band, rift eyes glaring under a V-shaped brow, a long braided black beard, dark plate, and his rune-hammer at his shoulder.
  hero_manus: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ...........RRRRRRRRRR...........
      .........RRrrrrAArrrrRR.rrrrrrrr
      ........RRRRRRrAArRRRRRRRNNNcNNR
      .......RRRRRRRrAArRRRRRRRNNcNNNR
      .......RRRRRRRrAArRRRRRRRNNwwNNR
      ......RRRRRRRRRAARRRRRRRRNNNcNNR
      ......RGGGGGGGGGGGGGGGGGRNNcNNNR
      ......RRRRRRRRRAARRRRRRRRRRRRRRR
      ......RNRRRRRRRAARRRRRRRNR..OG..
      ......RNddRRRRRAARRRRRddNR..GG..
      ......RNdcwdRRRAARRRdwcdNR..GG..
      ......RNddcwcdRAARdcwcddNR..GG..
      ......RNNddddddAAddddddNNR..GG..
      ......RdNddddddRRddddddNdR..GG..
      .....RRdNddNddddddddNddNdRR.GG..
      .....RddNddNddddddddNddNddR.GG..
      ..RRRRdNddNddddNNddddNddNdRRGG..
      .RNNNRddNddNddNddNddNddNddRNNNR.
      RNNRNRdNddNdddNddNdddNddNdRNRNNR
      RNRRNRdNddNddNddddNddNddNdRNRRNR
      RNNNRdNddNdddNddddNdddNddNdRNNNR
      RRRRRdNddNdddNddddNdddNddNdRRRRR
      RNNNNRdNddNddNddddNddNddNdRNNNNR
      RNcNNRddNddNddNddNddNddNddRNNcNR
      RNNNNNRdNddNddNddNddNddNdRNNNNNR
      RNNNNNRddNddNddNNddNddNddRNNNNNR
      RNNNNNNRddNddNddddNddNddRNNNNNNR
      RNNNNNNNRddGGddNNddGGddRNNNNNNNR
      RNNNNNNNNRddddNddNddddRNNNNNNNNR
      RNNNNNNNNRddNddddddNddRNNNNNNNNR
      RNNNNNNNNNRdddNddNdddRNNNNNNNNNR
    `,
  },
  // Nightlord Grun: a faceless dark lord in a tall spiked iron crown-helm, only slanted burning eyes in the visor's dark, spiked pauldrons over a black mantle.
  hero_grun: {
    palette,
    outline: OUTLINE,
    pixels: `
      ..R.....R......RR......R.....R..
      ..R.....R.....RRRR.....R.....R..
      ..RR....RR....RrrR....RR....RR..
      ...R.o..Rr..R.RrrR.R..rR..R.R...
      ...RRR..Rr..RRRrrRRR..rR..RRR...
      ...RrR.RRr.RRrRrrRrRR.rRR.RrR...
      ....RRRRrRRRrRRrrRRrRRRrRRRo....
      ....RNRNrNRNrNNrrNNrNRNrNRNR....
      ....RNNNNNNNNNNNNNNNNNNNNNNR....
      ..o.RrrrrrrrrrrRRrrrrrrrrrrR....
      .....RNNNNNNNNNRRNNNNNNNNNR.....
      .....RNddNNNNNNRRNNNNNNddNR.....
      .....RddOodddNNRRNNdddoOddR..o..
      .....RNdddoOodNRRNdoOodddNR.....
      .....RNNNddddNdRRdNddddNNNR.....
      .R...RNNNNNNNNdRRdNNNNNNNNR...R.
      .RR...RNNdNdNNdRRdNNdNdNNR...RR.
      ..R...RNNdNdNNdRRdNNdNdNNR...R..
      ..RR.R.RNNNNNNdRRdNNNNNNR.R.RR..
      ..RrRR..RNNNNNdRRdNNNNNR..RRrR..
      ..RrRr...RNNNNdRRdNNNNR...rRrR..
      .RRrrrR...RRNNdRRdNNRR...RrrrRR.
      RRNNNNRR..ddRRRRRRRRdd..RRNNNNRR
      RNNNNNNRRdNNNdNNNNdNNNdRRNNNNNNR
      RrrrrrNNRdNNNNdNNdNNNNdRNNrrrrrR
      RNNNNNNNRdNNNNNNNNNNNNdRNNNNNNNR
      RRNNNNNNRddNNNNooNNNNddRNNNNNNRR
      .RRRRRRRRdNdNNNNNNNNdNdRRRRRRRR.
      ..ddddddddNddNddddNddNdddddddd..
      .dddNdddddNdddNddNdddNdddddNddd.
      ddddNddddNddddNddNddddNddddNdddd
      dddNddddNdddddNddNdddddNddddNddd
    `,
  },
  // Rift Demon: a hulking horned demon made of the night sky, a rift burning in its chest, claws out.
  card_t_riftdemon: {
    palette,
    outline: OUTLINE,
    pixels: `
      ......pP..................Pp....
      ......P.P.................P.....
      .......PP................PP.....
      ........PP..............PP......
      .........PPPNNnnnnnnn.PPP.......
      ...........PPPnnnnnnPPP.........
      ............POonnnOoP...........
      ............Noonnnoon...........
      ............NNnnnnnnn...........
      ............NNdddddnn...........
      ............NNwdddwnn...........
      .....NNNNNnnNNnnnnnnnnnnnnn.....
      ....NNNNNNnnnnnnnnnnnnnnnnn.NNN.
      ....NNNNNNnnnnnnnnnnnnnnnn..NNN.
      ....NNNNNNwnnnnnpnnnnnnnnn..NNN.
      ....NNNNNNNnnnnnpnnnnwnnnn..NNN.
      ....NNNNNNNnnnnpwnnnnnnnnn..NNN.
      ....N.NNNNNnnnnpnnnnnnnnn...N.N.
      ...NNN.NwNNnnnnnwnnnnnnnw....NNN
      ...NNN.NNNNnnnnnpnnnnnnnn....NNN
      ...NNN..NNNnnnnnnpnnnnnn.....NNN
      ...NNN..NNNnwnnnnnnnnnnn.....NNN
      ...NNN..NNNNnnnnnnnnwnnn.....NNN
      ..aaa...NNNNnnnnnnnnnnnn....aaa.
      ..aaa....NNNnnnnnnnnnnn.....aaa.
      .a.a.a...NNNnnnnnnnnnnn....a.a.a
      .a.a.a....NnnnN...NnnnN....a.a.a
      ..........NnnnN...NnnnN.........
      ..........NnnnN...NnnnN.........
      ..........NnnnN...NnnnN.........
      ..........NnnnN...NnnnN.........
      ..........NNNNN...NNNNN.........
    `,
  },
  // Wrath of the Night: a horned demon skull against a crescent moon.
  power_grun: {
    palette,
    outline: OUTLINE,
    pixels: `
      ........................
      ........................
      ........................
      ......PPWWWWW.....PP....
      ......PPWww.......PP....
      .....WPPw.........PP....
      ....WWPP..........PP....
      ....Ww.PP........PP.....
      ...WWw.PP...V....PP.....
      ...Ww...PPVVVVVVPP......
      ...Ww...VPPvvvVPP.......
      ...Ww...VVvvvvvVV.......
      ..WWw...VoovvvooV.......
      ...Ww..VVoovvvooVV......
      ...Ww...VvvvvvvvV.......
      ...Ww...VVvvvvvVV.......
      ...WWw..VVdddddVV...WW..
      ....Ww...VwdddwV...wW...
      ....WWw.....V.....wWW...
      .....WWww.......wwWW....
      ......WWWwwwwwwwWWW.....
      ........WWWWWWWWW.......
      ............W...........
      ........................
    `,
  },
};
