// Shade card art, 32x32. Referenced by `sprite:` in cards.js.
// Preview at /sprites.html.

import { SKIN, SHADE, OUTLINE } from './palettes.js';

const palette = [SKIN, SHADE];

export default {
  // Knife in the Dark: a blade thrust from living shadow.
  card_r_knife: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ...............U................
      .........U..UUUNUUU.............
      ......UUUUUUUNNNNNUU............
      ....UUUNNNNUNNNNNNNU............
      ...UUUNNNNNUNNNNNNNU............
      ...UUNNNNNUNNNNNNNNNU...........
      ..UUNNNNNNNUNNNNNNNU............
      ..UNNNNNNNNUNNNNNNNU............
      ..UNNNXXXNNXXXNNNNUU............
      .UUNNNNxNNNNxUUNUUU.............
      ..UNNUNNNNgUUNUUU...............
      ..UUUNUUUUUcNNNNUU..............
      .UUNNNNNUUNNcNNNNU..............
      .UNNNNNNNUNNNcNgDU..............
      .UNNNNNNUNNNNNNgDDU.............
      UNNNNNNNNUNNNggdDDD.............
      .UNNNNNNNUNNNXXXdDDD............
      .UNNNNNNNUUNNNXXXdDDD...........
      .UUNNNNNUUUUUNUXXXdDDD..........
      ..UUUNUUU....U..XXXdDDD...x.....
      .....U...........XXXdDDD..x.....
      ..................XXXdDDxxXxx...
      ...................XXXdDDDx.....
      ....................XXXdDDx.....
      .....................XXXdDDD....
      ......................XXXdDD....
      .......................XXXdDD...
      ........................XXXdD...
      ..........................XXd...
      ................................
      ................................
    `,
  },
  // Shadow Shiv: a thrown knife trailing shadow.
  card_r_shiv: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      ................................
      ................................
      ................................
      ................................
      ................................
      ................................
      .........................DDDd...
      ........................DDdX....
      ............v.........DDDdXX....
      ...........v.........DDDdXX.....
      ...........v........DDdXXX.x....
      ..........v....q..DDDdXX..xXx...
      .........v..qqq..DDdXXX....x....
      ........v..q....DDdXXX..........
      ........vqq...ggDdXX............
      .......v....vv.gXXX.............
      ....qqq....v..c.g...............
      ...q.....vv.cc..g...............
      .qq....vv..gc...................
      ......v....q....................
      ....vv...qqV....................
      ...v....q..V....................
      .......q..V.....................
      ......q...V.....................
      .....q....V.....................
      ..........V.....................
      .........V......................
      .........V......................
      ................................
      ................................
    `,
  },
  // Nightshade Oil: a vial of green poison.
  card_r_oil: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      .............CCCCCC.............
      .............cccccc.............
      .............cccccc.............
      .............cccccc.............
      ............AAAAAAAA............
      ............AAAAAAAA............
      .............Aaaaaa.............
      .............Aaaaaa.............
      .............Aaaaaa.............
      .............Aaaaaa.............
      .............Aaaaaa.............
      ............AAaaaaaA............
      ..........AAaaaaaaaaAA..........
      .........AAXaaaaaaaaaAA.........
      ........AAXaaaaaaaaaaaAA........
      ........AaaaaaaaaaaaaaaA........
      .......ApppppppppppppPPPA.......
      .......ApppppppppppppPXPA.......
      .......AppppwwwwwwwwpPPPA.......
      .......AppppwwWWWWwwpPPPA.......
      .......ApXppwweWWewwpPPPA.......
      .......AppppwwWWWWwwpPPPA.......
      .......AppppwwWeeWwwpPPPA.......
      .......AppppwwwwwwwwpPPPA.......
      ........ApppwwwwwwwwpPPA........
      ........AApppppppppppPAA........
      .........AAPPPPPPPPPPAA.........
      ..........AAPPPPPPPPAA.p........
      ............AAAAAAAA...p........
      .......................p........
      .......................P........
    `,
  },
  // Alley Cutpurse: a grinning thief with a stolen purse.
  card_r_cutpurse: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      ...........qqqqqqqqqq...........
      .........qqvvvvvvvvvvqq.........
      ........qvvvvvvvvvvvvvvq........
      .......qvvvvvvvvvvvvvvvvq.......
      .......qvvvVVVVVVVVVVvvvq.......
      .......vvvVssssssssssVvvv.......
      .......vvvVseesssseesVvvv.......
      .......vvvVssssssssssVvvv.......
      .......vvvVssssSSsSssVvvv.......
      .......vvvvVssSSSSSsVvvvv.......
      .......vvvvVsSSSSSSsVvvvv.......
      ......vvvvvvVssssssVvvvvvv......
      .....vvvvvvvvVVVVVVvvvvvvvv.....
      ....vvvvvvvvvvvvvvvvvvvvvvvg....
      ...vvvvvvvvvvvvvvvvvvvvvvvvvv...
      ..vvvvvvvvvvvvvvvvvvvvvvvvvvgv..
      ..vvvvvVvvvvvvvvvvvvvvvvgggvvv..
      ..vvvvvVvvvvvvvvvvvvvvvCCCCCvg..
      ..vvvvvVvvvvvvvvvvvvvvvCCCCCvv..
      ..vvvvvVvvvvvvvvvvvvvvCCcccCCv..
      ..vvvvvVvvvvvvvvvvvvvCCcccccCC..
      ..vvvvvVvvvvvvvvvvvvvCcccccccC..
      ..vvvvvVvvvvvvvvvvvvvCcccccccC..
      ..vvvvvVvvvvvvvvvvvvvssccccccC..
      ..vvvvvVvvvvvvvvvvvvvsscccccCC..
      ..vvvvvVvvvvvvvvvvvvvssCcccCCv..
      ..vvvvvVvvvvvvvvvvvvvvvCCCCCvv..
      ..vvvvvVvvvvvvvvvvvvvvvvVvvvvv..
      ..vvvvvVvvvvvvvvvvvvvvvvVvvvvv..
      ..vvvvvVvvvvvvvvvvvvvvvvVvvvvv..
    `,
  },
  // Fade Step: a figure dissolving into shadow.
  card_r_fadestep: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      .............v..................
      ..........vvvvv.................
      .........vvvvvvv................
      ........vvvvvvv.................
      ........vvvNNNNNN........q......
      ........vvvNNNNNN...............
      ........vvvNxNNxN...u...........
      .........vvNNNNNN...............
      .........vvNNNNNNv...........q..
      .........vvvvvv.v...............
      ........vvvvvv.vv......q........
      .......vvvvvvvvv................
      .......vvvvvvvvv...........q....
      ......vvvvvvvvv..v..............
      ......vvvvvvvvv.v...............
      ......vvvvvvvv.vv...............
      ......vvvvvvvvvv........u.......
      ......vvvvvvvvvv..............q.
      ......vvvvvvvvv..v..............
      ......vvvvvvvvv.v...............
      ......vvvvvvvv.vv.........u.....
      ......vvvvvvvvvv................
      .....vvvvvvvvvvv................
      .....vvvvvvvvvv..v..............
      .....vvvvvvvvvv.v...........u...
      .....vvvvvvvvv.vv...............
      .....vUvvvvvvvvv......u.........
      .....vvvvvvvvvvv................
      ...U.vvvvUvvvvv..v.......q......
      .....vvvvvvvvvv.v...............
    `,
  },
  // Fan of Blades: five daggers fanned out.
  card_r_fan: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      ................................
      ................................
      ................................
      ................................
      ...............DX...............
      ...............DX...............
      ...............DX...............
      ....dX........DDXX........Dd....
      ....DdX.......DDXX.......DdX....
      .....DXX......DDXX......DDX.....
      .....DdXX.....DDXX.....DDdX.....
      .....DDdX.....DDXX.....DdXX.....
      ......DDXX....DDXX....DDXX......
      ......DDdXX...DDXX...DDdXX......
      .......DDXX...DDXX...DDXX.......
      ........DdXX..DDXX..DDdX........
      XX......DDdX..g.gXg.DdXX......DD
      XXXX.....DDXgg....ggDXX.....DDDD
      DdXXXX....gg....c...gg....DDDDdX
      DDDdXXXX.g..c...c..c..g.DDDDdXXX
      ..DDDdXXg...c...c..c...gDDdXXX..
      ....DDDdg....c..c.c....gdXXX....
      ......Dg.cc..cg.ggc..cc.gX......
      .......g...cc.GGGG.cc...g.......
      .............GGggGG.............
      .............GggggG.............
      .............GGggGG.............
      ..............GGGG..............
      ................................
      ................................
    `,
  },
  // Gutter Prodigy: a masked street kid with a crooked grin.
  card_r_prodigy: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      ...........N.N....N.N...........
      ........N.NNNNNNNNNNNN.N........
      .......NNNNNNNNNNNNNNNNNN.......
      ......NNNNNNNNNNNNNNNNNNNN......
      ......NNNNNssNssssNssNNNNN......
      ......NNNssssssssssssssNNN......
      ......NNwwwwwwwwwwwwwwwwNN......
      ......NNweewwwwwwwwwweewNN......
      ......NNwwwwwwXwwXwwwwwwNN......
      ......NNssssssssssssssssNN......
      ......NNsssssssSSssRssssNN......
      .......NssssssRRRRRsssssN.......
      ........ssssssssssssssss........
      ..........SSssssssssSS..........
      ........xxxxxxxxxxxxxxxx........
      ......vvvvvvxxvvvvxxvvvvvv......
      ....vvvvvvvvvvvvvvvvvvvvvvvv....
      ...vvvvvvvvvvvvvvvvvvvvvvvvvv...
      ..vvvvvvvvvvvvvvvvvvvvvvvvvvvv..
      ..vvvvvvvvvvvvvvvvvvvvvvvvvvvv..
      ..vvqvvvvvvvvvvvvvvvvvvvvvvqvv..
      ..vvqvvvvvvvvvvvvvvvvvvvvvvqvv..
      ..vvqvvvvvvvvvvvvvvvvvvvvvvqvv..
      ..vvqvvvvvvvvvvvvvvvvvvvvvvqvv..
      ..vvqvvvvvvvvvvvvvvvvvvvvvvqvv..
      ..vvqvvvvvvvvvvvvvvvvvvvvvvqvv..
      ..vvqvvvvvvvvvvvvvvvvvvvvvvqvv..
      ..vvqvvvvvvvvvvvvvvvvvvvvvvqvv..
      ..vvqvvvvvvvvvvvvvvvvvvvvvvqvv..
      ..vvqvvvvvvvvvvvvvvvvvvvvvvqvv..
    `,
  },
  // Silent Contract: a sealed contract pinned by a dagger.
  card_r_contract: {
    palette,
    outline: OUTLINE,
    pixels: `
      ...............g................
      ...............c................
      ...............c................
      ...............c................
      ...............c................
      ................................
      ....WWWWWWWWgggggggWWWWWWWWW....
      ....WWWWWWWWWWXdDWWWWWWWWWWW....
      ....WWWWWWWWWWXdDWWWWWWWWWWW....
      .....WWWWWWWWWXdDWWWWWWWWWW.....
      .....wwwwwwwwwXdDwwwwwwwwww.....
      .....wwwwwwwwwXdDwwwwwwwwww.....
      .....wwwWWWWWWXdDWWWWWWWwww.....
      .....wwwwwwwwwXdDwwwwwwwwww.....
      .....wwwwwwwwwXdDwwwwwwwwww.....
      .....wwwWWWWWWXdDWWWWwwwwww.....
      .....wwwwwwwwwXdDwwwwwwwwww.....
      .....wwwwwwwwwXdDwwwwwwwwww.....
      .....wwwWWWWWWXdDWWWWWwwwww.....
      .....wwwwwwwwwXdDwwwwwwwwww.....
      .....wwwwwwwwwXdDwwwwwwwwww.....
      .....wwwWWWWWWWdWWWWWWWwwww.....
      .....wwwwwwwwwwdwwwwRRRwwww.....
      .....wwwwwwwwwwwwwwRrrrRwww.....
      .....wwwwwwwwwwwwwRrRrRrRww.....
      .....wwwNNNNNNNNwwRrrrrrRww.....
      .....wwwwwwwwwwwwwRrrRrrRww.....
      .....wwwwwwwwwwwwwwRrrrRwww.....
      .....WWWWWWWWWWWWWWWRRRWWWW.....
      ....WWWWWWWWWWWWWWWWWWWWWWWW....
      ....WWWWWWWWWWWWWWWWWWWWWWWW....
      ....WWWWWWWWWWWWWWWWWWWWWWWW....
    `,
  },
  // Shiv: a small, mean knife.
  card_t_shiv: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      ................................
      ...............DX...............
      ..............DDXX..............
      ..............DDXX..............
      .............DDDXXX.............
      .............DDDXXX.............
      .............DDDXXX.............
      .............DDDXXX.............
      .............DDDXXX.............
      .............DDDXXX.............
      .............DDDXXX.............
      .............DDDXXX.............
      .............DDDXXX.............
      .............DDDXXX.............
      .............DDDXXX.............
      .............DDDXXX.............
      .............DDDXXX.............
      .............DDDXXX.............
      ............g.g.g.g.g...........
      ................c...............
      ..............cccc..............
      ..............CCCC..............
      ..............cccc..............
      ..............CCCC..............
      ..............cccc..............
      ..............CCCC..............
      ..............cccc..............
      .............gggggg.............
      .............gggggg.............
      ................................
    `,
  },
};
