// Stalker card art, 32x32. Referenced by `sprite:` in cards.js.
// Preview at /sprites.html.

import { SKIN, STALKER, OUTLINE } from './palettes.js';

const palette = [SKIN, STALKER];

export default {
  // Hunting Hawk: a fierce profile with a hooked beak.
  card_s_hawk: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      ................................
      ................................
      ..............BBBBBBBB..........
      ............BbBBBBbbB...........
      ..........BbBBBBbbBBBBB.........
      .........BBBobbbbbbbbbb.........
      ......YY.BbweobbbbbbbbbB........
      ....YYYYYboeeeobbbbbbbbb........
      ...YYYYYYbboeobbbbbbbbbbB.......
      ..YYYCCCCxxxoxxxbbbbbbbbB.......
      ..YoY...BxxxxxxxbbbbbbbbB.......
      ..Yo....BxxxxxxxbbbbbbbbB.......
      ...o....BxxxBBxxbbbbbbbbB.......
      .........bbbBbBbbbbbbbbb........
      .........BbbbBBbbbbbbbbB........
      ..........bbbbBbbbbbbbb.........
      ..........BbbbBBbbbbbbBxx.......
      ...........xBbBbBbbbBxxxxx......
      ..........xbxxBBBBBxbxxbxxb..b..
      .........xxbxxbxxbxxbxxbxxbx.b..
      .........xxxxxxxxxxxxxxxxxxx....
      ........xxxxxxxxxxxxxxxxxxxxx...
      ........xxbxxbxxbxxbxxbxxbxxb...
      ........xxbxxbxxbxxbxxbxxbxxb...
      ........xxxxxxxxxxxxxxxxxxxxx...
      .......xxxxxxxxxxxxxxxxxxxxxxx..
      ........xxxbxxbxxbxxbxxbxxbxxb..
      ........xxxbxxbxxbxxbxxbxxbxxb..
      ........xxxxxxxxxxxxxxxxxxxxx...
      ........xxxxxxxxxxxxxxxxxxxxx...
    `,
  },
  // Pinning Shot: an arrow driven into a post.
  card_s_pinning: {
    palette,
    outline: OUTLINE,
    pixels: `
      ........................CcccccC.
      ........................CcccccC.
      ........................CcccccC.
      ...z....................CcccccC.
      ....zz..................CcCCccC.
      ....zz..................CcccCcC.
      ...czz..................CcccccC.
      ..zzzzCC................CcccccC.
      xx..zzzcC...............CcccccC.
      ..xz....cCC.............CcccccC.
      ...xx.....cCC...........CcccccC.
      .x.........ccCC.........CcCcccC.
      ..xxx........ccC........CccCCcC.
      .....x.........cCC....a.CcccccC.
      .................cCC....CcccccC.
      ...x..............ccCC..CcccccC.
      ....xxx.............ilallcccccC.
      .......x.............iillcccccC.
      .....................iiiilccccC.
      ......................iiiiCcccC.
      .....................a..CccCCcC.
      .......................aCcccccC.
      ........................CcccccC.
      ........................CcccccC.
      ........................CcccccC.
      ........................CcccccC.
      ........................CcCCccC.
      ........................CcccCcC.
      ........................CcccccC.
      ........................CcccccC.
      ........................CcccccC.
      ........................CcccccC.
    `,
  },
  // Snapjaw Croc: open jaws in profile.
  card_s_snapjaw: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      ................................
      ................................
      ................................
      .......gggg.....................
      .......goeg.....................
      .......gggg.....................
      GGGGGGGggggGG...................
      gggggggggggggGGGGGGGGG..........
      gggggggggggggggggggggGGGGGGGGGG.
      gggggggggggggggggggggggggggggGG.
      ggggggggggggggggggggggggggggggg.
      gggggggggwwwwwwwwwwwwwwwwwwww...
      gggggggggzwzzwzzwzzwzzwzzwzzz...
      gggggggggzzzzzzzzzzzzzzzzzzzz...
      gggggggggzzwzzwzzwzzwzzwzzwzz...
      gggggggggwwwwwwwwwwwwwwwwwwwz...
      ggggggggggggggggggggggggggggg...
      ggggggggggggggggggggggggggggg...
      ggggggggggggggggggggggggjjjjj...
      ggggggggggggggjjjjjjjjjj........
      ggggjjjjjjjjjj..................
      gggggggggg......................
      jjjjjjjjjjjjj...................
      ggggggggggggg...................
      ggggggggggggg...................
      ................................
      ................................
      ................................
      ................................
      ................................
    `,
  },
  // Scout's Instinct: a watchful eye among leaves.
  card_s_instinct: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      ................................
      ..vVV......................qqv..
      ..qvVV....................qqvV..
      ..qqvVV..................qqvVV..
      ...qqvV..................qvVV...
      ....qqv..................vVV....
      ................................
      ..........CCCxxxxxxCCC..........
      .......CCxxxxxVVVVxxxxxCC.......
      ......CxxxxxVVvvvvVVxxxxxC......
      .....CxxxxxVvvvvvvvvVxxxxxC.....
      ....CxxxxxxVvwwqqqvvVxxxxxxC....
      ...CCxxxxxVvvweeeeqvvVxxxxxCC...
      ...CxxxxxxVvvqeeeeqvvVxxxxxxC...
      ...CxxxxxxVvvqeeeeqvvVxxxxxxC...
      ...CCxxxxxVvvqeeeeqvvVxxxxxCC...
      ....CxxxxxxVvvqqqqvvVxxxxxxC....
      .....CxxxxxVvvvvvvvvVxxxxxC.....
      ......CxxxxxVVvvvvVVxxxxxC......
      .......CCxxxxxVVVVxxxxxCC.......
      ..........CCCxxxxxxCCC..........
      ................................
      ....VVv..................vqq....
      ...VVvq..................Vvqq...
      ..VVvqq..................VVvqq..
      ..Vvqq....................VVvq..
      ..vqq......................VVv..
      ................................
      ................................
      ................................
    `,
  },
  // Call the Pack: a wolf howling at the full moon.
  card_s_pack: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      .............F..NNNNNNN.........
      ....FF.......FFNMMMMMMMNN.......
      ...FFfF.....FFFfMMMMMMMMMN......
      ..FFFFfff..FFFFfMMMMMMMMMMN.....
      .FFFFFFFFfFFFFFfMMMMMMMMMMMN....
      .FeeFFFFFFFFFFFFMMMMMMMMMMMMN...
      ..FFeFFFFooFFFFFfMMMMMMMMMMMN...
      ...FFeeFFFFFFFFFfFMMMMMMNMMMMN..
      ....FFFFFFFFFFFFFfFMMMMMMMMMMN..
      .....FFFFFFFFFFFFfFMMMMMMMMMMN..
      ......FFFFFFFFFFFFfFMMMMMMMMMN..
      ......FFFFFFFFFFFFfFMMMMMMMMMN..
      .......FFFFFFFFFFFfFFMNMMMMMMN..
      ........FFFFFFFFFFFfFFMNMMMMMN..
      ........FFFFFFFFFFFfFFMMMMMMN...
      ........FFFFFFFFFFFfFFFMMMMMN...
      .........FFFFFFFFFFFfFFMMMMN....
      .........FFFFFFFFFFFfFFMMMN.....
      .........FFFFFFFFFFFfFFFMN......
      ..........FFFFFFFFFFFfFFN.......
      ..........FFFFFFFFFFFfFF........
      ..........FFfFFFFFFFFFfF........
      ..........FFFfFFFFFFFFfFF.......
      ..........FFFFFFFFFFFFfFF.......
      ..........FFfFFFFFFFFFFfF.......
      ..........FFFfFFFFFFFFFfFF......
      ..........FFFFFFFFFFFFFFfF......
      ..........FFfFFFFFFFFFFFfF......
      ..........FFFfFFFFFFFFFFfF......
      ..........FFFFFFFFFFFFFFFfF.....
      ..........FFfFFFFFFFFFFFFfF.....
    `,
  },
  // Packmaster: a hunter in a wolf-pelt hood.
  card_s_packmaster: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      ..........f..........f..........
      ..........ff........ff..........
      .........ffffffffffffff.........
      ........ffJffffffffffJff........
      ........ffffeffffffeffff........
      .......ffffffffFFffffffff.......
      .......fffffffFFFFfffffff.......
      ......fffffffFFFFFFfffffff......
      ......ffSssssssssssssssSff......
      ......ffffseesssssseesffff......
      ......ffffssssssssssssffff......
      ......ffffsssssSSsssssffff......
      ......ffffBsssBBBBsssBffff......
      ......ffffBBBBBBBBBBBBffff......
      .....fffffBBBBBBBBBBBBfffff.....
      ....ffffffBBBBBBBBBBBBffffff....
      ...fffffffcBBBBBBBBBBcfffffff...
      ..ffffffcccBBBBccBBBBcccffffff..
      .fffffccccccccccccccccccccfffff.
      fffffCCCcccCccccccccCccccccfffff
      fffccccCCCCccccccccccCcccccccfff
      ffcccccccCCCcccccccccCccccccccff
      fcccccccccCCCCcccccccCcccccccccf
      fcccccccccCccCCCcccccCcccccccccf
      ccccccccccCccccCCCcccCcccccccccc
      ccccccccccCccccccCCCcCcccccccccc
      ccccccccccCccccccccCCCcccccccccc
      ccccccccccCccccccccccCCCcccccccc
      ccccccccccCccccccccccCcCCCcccccc
      ccccccccccCccccccccccCcccCCCcccc
    `,
  },
  // Twin Arrows: two arrows in flight.
  card_s_twinarrows: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      ................................
      .......................llli.....
      ......................lliii.....
      ....................Cliiii......
      ..................CCciiiii......
      ................CC.c............
      ..............CC.cc.............
      ............CC.cc...............
      ..........CC.cc.................
      ........CC.cc...................
      ......CC.cc.....................
      ..z..C.cc.......................
      z..zzcc.........................
      .zzczz..........................
      ..czz.....................llli..
      ...zz....................lliii..
      ..zxz..................Cliiii...
      .xx..................CCciiiii...
      x..................CC.c.........
      .....x...........CC.cc..........
      ...xx..........CC.cc............
      ..x..........CC.cc..............
      ...........CC.cc................
      ....x....CC.cc..................
      ..xx.z..C.cc....................
      .x.z..zzcc......................
      ....zzczz.......................
      .....czx........................
      .....xxz........................
      ....xz.z........................
    `,
  },
  // Thunderhoof Stag: antlers crackling with lightning.
  card_s_stag: {
    palette,
    outline: OUTLINE,
    pixels: `
      ...a......a....Y.....a......a...
      ...a...a..a.....Y....a..a...a...
      ...aa..a.a.....YY.....a.a..aa...
      ....a.aa.a....Y.......a.aa.a....
      ....aaa.aa............aa.aaa....
      .....aaaa..............aaaa.....
      ......aa................aa......
      .......a................a.....Y.
      .Y......aa...dddddd...aa.....Y..
      ..Y......aaddddddddddaa.....Y...
      ...Y......dddddddddddd.......Y..
      ..Y..DDDDddddddddddddddDDDD...Y.
      .Y....DDddddddddddddddddDD...Y..
      ..Y.......dddddddddddd......Y...
      ...Y......dedddddddded..........
      ..........dddddddddddd..........
      ...........dddddddddd...........
      ...........dddddddddd...........
      ............dddddddd............
      ............aaaaaaaa............
      ............aaaaaaaa............
      .............aCCCCa.............
      .............aaaaaa.............
      ...........dddddddddd...........
      ..........dddddddddddd..........
      .........dddddddddddddd.........
      ........ddddddaaaadddddd........
      .......dddddddaaaaddddddd.......
      ......ddddddddaaaadddddddd......
      .....dddddddddaaaaddddddddd.....
      ....ddddddddddaaaadddddddddd....
      ...dddddddddddaaaaddddddddddd...
    `,
  },
  // Dusk Wolf: a grey wolf with amber eyes.
  card_t_wolf: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      ................................
      .......f................f.......
      .......ff..............ff.......
      .......fFf............fFf.......
      .......fFFf..........fFFf.......
      .......fFFff........ffFFf.......
      .......ffffffffffffffffff.......
      ......ffffffffffffffffffff......
      ......fFFFffffffffffffFFFf......
      ......fffffoeffffffeofffff......
      ......ffffffJJJJJJJJffffff......
      ......FfffffJJJJJJJJfffffF......
      .......FfffJJJJJJJJJJfffF.......
      ........FffJJJJJJJJJJffF........
      ........FfJJJJkkkkJJJJfF........
      .........FJJJJkkkkJJJJF.........
      ..........JJJFFFFFFJJJ..........
      ...........JJJJJJJJJJ...........
      ............JJJJJJJJ............
      .......ffff.JJJJJJJJ.ffff.......
      .....ffffffffJJJJJJffffffff.....
      ...ffffffffffJJJJJJffffffffff...
      ..fffffffffffJJJJJJfffffffffff..
      .ffffffffffffJJJJJJffffffffffff.
      .ffffffffffffJJJJJJffffffffffff.
      fffffffffffffJJJJJJfffffffffffff
      fffffffffffffJJJJJJfffffffffffff
      fffffffffffffJJJJJJfffffffffffff
      fffffffffffffJJJJJJfffffffffffff
      fffffffffffffJJJJJJfffffffffffff
    `,
  },
};
