// Vanguard card art (wave 1 of card art), 32x32. Referenced by `sprite:` in cards.js.
// Preview at /sprites.html.

import { SKIN, VANGUARD, OUTLINE } from './palettes.js';

const palette = [SKIN, VANGUARD];

export default {
  // Aegis Blessing: a radiant crusader shield.
  card_v_aegis: {
    palette,
    outline: OUTLINE,
    pixels: `
      ...............g................
      ................................
      ...............g................
      ........g.............gg........
      ...y.....y.....y......y.........
      ........gggggggggggggggg........
      ........glbttttttttttttg....y...
      ........gtbttttggttttttg........
      ...g....gtbttttggttttttg....g...
      ....yy..gtbttttggttttttg..yy....
      ......y.gtbttttggttttttg.y......
      ........gtbggggggggggttg........
      ........gtbggggggggggttg........
      ........gtbttttggttttttg........
      ........gtbttttggttttttg........
      ..y.....gtbttttggttttttg........
      g.g.y....gbttttggtttttg...y.yyg.
      .........gbttttggtttttg.........
      ..........gttttggttttg..........
      ..........gttttggttttg..........
      ...........gtttggtttg...........
      ......y....ggttggttgg....y......
      ...gyy......gttggttg......yyg...
      ...g.........gttttg.........g...
      .............ggttgg.............
      ..........y...gttg...y.....y....
      ....y.....y....gg.....y.........
      .........y............y.........
      ........gg......y.....gg........
      ................................
      ................g...............
      ................................
    `,
  },
  // Militia Captain: kettle hat, moustache and spear.
  card_v_captain: {
    palette,
    outline: OUTLINE,
    pixels: `
      ..........................ll....
      .........................liil...
      .........................liiI...
      ..........................iI....
      ..........................cC....
      ..........................cC....
      ..........................cC....
      ..........IIIIIIIIIIII....cC....
      .........IiiiiiiiiiiiiI...cC....
      ........IiiiliiiiiiliiiI..cC....
      .....IiiiiiiiiiiiiiiiiiiiicC....
      .....IIIIIIIIIIIIIIIIIIIIIcC....
      ...........SSSSSSSSSS.....cC....
      ..........SseesssseesS....cC....
      ..........SssssssssssS....cC....
      ..........SssssSSssssS....cC....
      ..........SsCCCCCCCCsS....cC....
      ..........SCssssssssCS....cC....
      ............SSssssSS......cC....
      ........tttttttttttttttt..cC....
      ......tttttttttggtttttttttcC....
      ....tttTttttttttttttttttTssS....
      ...ttttTtttttttggtttttttTsSSt...
      ..tttttTttttttttttttttttTtcCtt..
      ..tttttTtttttttggtttttttTtcCtt..
      ..tttttTttttttttttttttttTtcCtt..
      ..ttTttTccccccggggccccccTtcCtt..
      ..ttTttTttttttttttttttttTtcCtt..
      ..ttTttTtttttttggtttttttTtcCtt..
      ..ttTttTttttttttttttttttTtcCtt..
      ..ttTttTtttttttggtttttttTtcCtt..
      ..ttTttTttttttttttttttttTtcCtt..
    `,
  },
  // Gleaming Shieldmaiden: nasal helm, golden braids, kite shield.
  card_v_shieldmaiden: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      ................................
      ................................
      ................................
      ............IIIIIIII............
      ..........IIiilllliiII..........
      .........IiiiilllliiiiI.........
      .........IiiiiiiiiiiiiI.........
      ........yIIIIIIiiIIIIIIy........
      ........yySsssSiiSsssSyy........
      ........yyseessiisseesyy........
      ..y.....yysssssSSsssssyy........
      ........yyssssssssssssyy........
      .y......yyssssmmmmssssyy........
      ...ggggggggggggggssssSyy........
      ...glwllllllllllgSSS..yy........
      ...glwlllgglllllgsys...yy.......
      ...glwlllgglllllgiiii..gy.......
      ...glwlllgglllllglliiiiiyy......
      ...glgggggggggglglliiiiiiyi.....
      ...glwlllgglllllgliiiiiiiiii....
      ...glwlllgglllllgiiyiiiiiiiii...
      ..iglwlllgglllllgiiiiiiiiIiiii..
      ..iigwlllggllllgiiiiiiiiiIiiii..
      ..iigglllgglllggiiiiiiiiiIiiii..
      ..iiiglllgglllgiiiiiiiiiiIiiii..
      ..iiiigllggllgiiiiiiiiiiiIiiii..
      ..iiiigglgglggiiiiiiiiiiiIiiii..
      ..iiiiIgllllgiiiiiiiiiiiiIiiii..
      ..iiiiIigllgiiiiiiiiiiiiiIiiii..
      ..iiiiIiiggiiiiiiiiiiiiiiIiiii..
    `,
  },
  // Rallying Banner: a swallow-tailed standard mid-wave.
  card_v_banner: {
    palette,
    outline: OUTLINE,
    pixels: `
      ......gg........................
      .....gyyg.......................
      ......gg..............ggg.......
      ......cC............gggggggg....
      ......cCgg........ggggTTTggggg..
      ......cCgggg...gggggTTTTTTTTgg..
      ......cCttggggggggttTTTTTTTTtt..
      ......cCttttgggtttttTTTTTTTTt...
      ......cCttttttttttttTTTTTTTTt...
      ......cCttttttttggttTTTTTTT.....
      ......cCttttttttggttgTTTTTT.....
      ......cCttttttttgggggTTTTT......
      ......cCtttttttgggggTTTTTT......
      ......cCtttttgggggttTTTTTTT.....
      ......cCtttttggtggttTTTTTTT.....
      ......cCttttttttggttTTTTTTTT....
      ......cCttttttttggttTTTTTTTT....
      ......cCttttttttggttTTTTTTTTt...
      ......cCttttttttggttTTgggTTTt...
      ......cCttttttttttttggggggggtt..
      ......cCggttttttttgggg...ggggg..
      ......cCggggtttggggg........gg..
      ......cC..gggggggg..............
      ......cC....ggg.................
      ......cC........................
      ......cC........................
      ......cC........................
      ......cC........................
      ......cC........................
      ......cC........................
      ......cC........................
      ......cC........................
    `,
  },
  // Oathkeeper Hammer: steel warhammer bound in gold, ruby set in the head.
  card_v_hammer: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      ....y...........................
      .............yyyyyy........y....
      ......IIlllllgggggglllllII......
      ......IliiiiiggggggiiiiiII......
      ......IliiiiigryrrgiiiiiII......
      ......IliiiiigryrrgiiiiiII......
      ......IliiiiigrrrrgiiiiiII......
      ......IliiiiigrrrrgiiiiiII......
      ......IliiiiiggggggiiiiiII......
      ......IIIIIIIggggggIIIIIII......
      .............gggggg.........y...
      ...y...........cC...............
      ...............cC...............
      ...............ww...............
      ..........y....cC...............
      ...............cC....y..........
      ...............ww...............
      ...............cC...............
      ...............cC...............
      ...............ww...............
      ...............cC...............
      ...............cC...............
      ...............ww...............
      ...............cC...............
      ...............cC...............
      ...............cC...............
      ...............cC...............
      ..............gggg..............
      ..............gggg..............
      ...............GG...............
    `,
  },
  // Hallowed Ground: a golden sigil with light rising from it.
  card_v_hallowed: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      ...............ww...............
      ...............ww.......y.......
      .......y.......ww...............
      ............w..yy..w............
      ............w..yy..w............
      ............w.gyyg.w............
      ............y.gyyg.y........y...
      .........w..y.gyyg.y..w.........
      ...y.....w.ggggyygggg.w.........
      .........w.yyyyyyyyyy.w.........
      .........y.ggggyygggg.y.........
      .........y..y.gyyg.y..y.........
      .........y..y.gyyg.y..y.........
      .........y..y.gyyg.y..y.........
      .....w...y..y.gyyg.y..y...w.....
      .....w...y..y.gyyg.y..y...w.....
      .....w...y..y.gyyg.y..y...w.....
      .....y...y..y..yy..y..y...y.....
      .....y...y..y..yy..y..y...y.....
      .....y...y..y..yy..y..y...y...y.
      .y...y...yggyggyyggyggy...y.....
      .....ygggyyyyyyyyyyyyyygggy.....
      ...ggyyyyyygygyyyygygyyyyyygg...
      ..gggyyyygyyyyyyyyyyyygyyyyggg..
      ..ggyyyygyyyyyyyyyyyyyygyyyygg..
      ..gggyyyygyyyyyyyyyyyygyyyyggg..
      ...gggyyyyygggyyyygggyyyyyggg...
      ......gggyyyyyyyyyyyyyyggg......
      ..........gggggggggggg..........
      ................................
    `,
  },
  // Silverlance Cavalier: barded warhorse, lance and pennant.
  card_v_cavalier: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ......................bbbbbb....
      .......................bbbbbb.lI
      ............il.il.......bbbB.lI.
      ...........iilil.........B..lI..
      ..........biiliii..........lI...
      .........bbiiiiill........lI....
      ........bbiiiiiilll......lI.....
      ........bbiiieeiiill....lI......
      .......bbiiiiiiiiilll..lI.......
      .......bbiiigiiiiiillllI........
      ......bbiiiigiiiiiiilll.........
      ......bbiiiigiiiiiiiilll........
      .....bbbiiiiggggggiiiilll.......
      .....bbbiiiiiiiiiigiiiilll......
      .....bbbiiiiiiiiiigiiiiilll.....
      ....bbbbiiiiiiIIIIgIiiiiiill....
      ....bbbbiiiiiiIlI..IIIiiiiik....
      ....bbbbiiiiiIlI.....IIIIkkk....
      ...bbbbiiiiiiII.................
      ...bbbbiiiiiiI..................
      ...bbbbiiiiiI...................
      ..ttttttttttttt.................
      ..gggggggggggggg................
      .ttttttttttttttt................
      .tttttgttttttttt................
      .ttttgggtttttttt................
      .tttttgttttttttt................
      ttttttttttttttttt...............
      tTttttttttttttttt...............
      gggggggggggggggggg..............
      ttttttttttttttttttt.............
    `,
  },
  // High Justicar: crowned elder, sword raised, crimson mantle.
  card_v_justicar: {
    palette,
    outline: OUTLINE,
    pixels: `
      ...............ll...............
      ..............illi..............
      ..............illi..............
      ..............illi..............
      ..............illi..............
      ..........g..gillig..g..........
      ..........ggyggrggrggyg.........
      ..........gggggggggggg..........
      ..........GGGGGGGGGGGG..........
      .........wwswwsssswwsww.........
      .........wsseesssseessw.........
      .........wsssssSSsssssw.........
      .........wwSwwwwwwwwSww.........
      .........wwwwwwwwwwwwww.........
      ........wwwwwwwwwwwwwwww........
      ........wwwwWwwwwwwWwwww........
      ......rgwwwwwwwwwwwwwwwwgr......
      .....rrgwwwwWwwwwwwWwwwwgrr.....
      ....rrrgGwwwwwwwwwwwwwwGgrrr....
      ...rrrrrgGwwwWwwwwWwwwGgrrrrr...
      ..rrrrrrrgGwwwwwwwwwwGgrrrrrrr..
      .rrrrrrrrrgGwwwwwwwwGgrrrrrrrrr.
      .rrrrrrrrrrgGiwwwwiGgrrrrrrrrrr.
      rrrrrrrrrrrrgiiiiiigrrrrrrrrrrrr
      rrrrRrrrrrrrgiiiiiigrrrrrrrRrrrr
      rrrRrrrrrrrrgiiiiiigrrrrrrrrRrrr
      rrrRrrrrrrrrgiiIIiigrrrrrrrrRrrr
      rrrRrrrrrrrrgiiiiiigrrrrrrrrRrrr
      rrRrrrrrrrrrgiiiiiigrrrrrrrrrRrr
      rrRrrrrrrrrrgiiiiiigrrrrrrrrrRrr
      rrRrrrrrrrrrgiiiiiigrrrrrrrrrRrr
      rrRrrrrrrrrrgiiiiiigrrrrrrrrrRrr
    `,
  },
  // Recruit: a fresh-faced soldier in a bowl helmet.
  card_t_recruit: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      ................................
      ................................
      ................................
      ................................
      ................................
      ............iiiiiiii............
      ..........iiilllllliii..........
      .........iiiiiilliiiiii.........
      .........iiiiiiiiiiiiii.........
      .........IIIIIIIIIIIIII.........
      ...........ssssssssss...........
      ...........seessssees...........
      ...........ssssssssss...........
      ...........sSssssssSs...........
      ...........sssSmmSsss...........
      ............SsSSSSsS............
      ............ssssssss............
      ........tttttttttttttttt........
      ......tttttttttttttttttttt......
      .....tttttttttttttttttttttt.....
      ....tttTttttttttttttttttTttt....
      ....tttTttttttttttttttttTttt....
      ....tttTttttttttttttttttTttt....
      ....tttTcccccccggcccccccTttt....
      ....tttTttttttttttttttttTttt....
      ....tttTttttttttttttttttTttt....
      ....tttTttttttttttttttttTttt....
      ....tttTttttttttttttttttTttt....
      ....tttTttttttttttttttttTttt....
      ....tttTttttttttttttttttTttt....
    `,
  },
};
