// Warlord card art, 32x32. Referenced by `sprite:` in cards.js.
// Preview at /sprites.html.

import { SKIN, WARLORD, OUTLINE } from './palettes.js';

const palette = [SKIN, WARLORD];

export default {
  // Shockwave Stomp: an armoured boot slamming the ground.
  card_w_stomp: {
    palette,
    outline: OUTLINE,
    pixels: `
      ..........lliiiiiiI.............
      ..........lliiiiiiI.............
      ..........lliiiiiiI.............
      ..........lliiiiiiI.............
      ..........lliiiiiiI.............
      ..........IIIIIIIII.............
      ..........lliiiiiiI........nN...
      ..........lliiiiiiI.............
      .....nN...lliiiiiiI.............
      ..........lliiiiiiI.............
      ..........lliiiiiiI......nN.....
      ......nN..lliiiiiiI.............
      .........IIIIIIIIIII............
      .........IIIIIgIIIII............
      .........IIIIIIIIIII.......nN...
      ....nN..lllllllIllllll..........
      ........iiiiiiiIiiiiIi..........
      ........iiiiiiiIiiiiIlllll......
      ......yyiiiiiiiIiiiiIiiiIiy..nN.
      ..nNyy..iiiiiiiIiiiiIiiiIiiyyy..
      ..yy....iiiiiiiIiiiiIiiiIii..yy.
      .yyy...yCCCCCCCCCCCCCCCCCCCC.yyy
      yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
      dddyyydddddyyddDDDddyydddddyyydd
      ddddddyyyydddDDdDdDddddyyyyddddd
      ddddddddddddyyyyyyyyyddddddddddd
      ddddDDDdddDDddddDddddDdddDDDdddd
      dddddddDDDddddddDdddddDDDddddddd
      ddddddddDdddddddDddddddDdddddddd
      ddddddddDdddddddDdddddddDddddddd
      ddddddddDdddddddDdddddddDddddddd
      dddddddDdddddddddddddddddDdddddd
    `,
  },
  // Notched Axe: a battle-worn crescent axe.
  card_w_axe: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      ................................
      ...................i............
      ...................III..........
      ...................III......ii..
      ...................III.....iiil.
      ...................III....iiiil.
      ........................Iiiiiiil
      .....................cCIIiiiiiil
      ....................cCIIIiiiiiil
      ....................IIIIiiiiiill
      ...................iIIIiiiiiii.l
      .................iiiiiiiiiiiiill
      ................iiiiiiiiiiiiill.
      ...............iiiiiiiiiiiiilll.
      ................ciiiiiiiiiilll..
      ...............cC.iiiiiiiilll...
      ...............cC...iiillll.....
      ..............cC.....llll.......
      .............cC.................
      .............cC.................
      ............cC..................
      ........CCCcC...................
      ..........c.C...................
      ..........CCC...................
      .........cC.....................
      ........cC..CCC.................
      ........cC......................
      ......ggg.......................
      ......ggg.......................
      ......ggg.......................
    `,
  },
  // Headsman's Verdict: the hooded executioner and his axe.
  card_w_verdict: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      ..........................lll...
      ............KKKKKKKK......iill..
      ..........KKKKKKKKKKKK....iiiil.
      .........KKKKKKKKKKKKKK..ciiiill
      ........KKKKKKKKKKKKKKKK.ciiiiil
      ........KKKKKKKKKKKKKKKK.ciiiiil
      ........KKKxxKKKKKKxxKKK.ciiiiil
      ........KKKKKKKKKKKKKKKK.ciiiiil
      ........KKKKKKKKKKKKKKKK.ciiiiil
      ........KKKKKKKKKKKKKKKK.ciiiill
      .......KKKKKKKKKKKKKKKKKK.iiiil.
      ......KKKKKKKKKKKKKKKKKKKKiill..
      ....KKKKKKKKKKKKKKKKKKKKKKKKl...
      ..sssKKKKKKKKKKKKKKKKKKKKKKsss..
      .ssssKKKKKKKKKKKKKKKKKKKCCKssss.
      sssssSKKKKKKKKKKKKKKKKCCCKSsssss
      ssssssssKKKKKKKKKKKKCCCKssssssss
      ssssssssssKKKKKKKKKCCKssssssssss
      ssssssssssssKKKKKCCCssssssssssss
      sssssssssssssSKKCCSsssssssssssss
      SsssssssssssssCCCSssssssSSSSsssS
      SsssssSsssssCCCSSssssssssSsssssS
      SsssssSssssCCssssssssssssSsssssS
      SssssssssCCCssSssSsssssssssssssS
      SssssssCCCsssSssssSssssssssssssS
      ccccccCCcccccccggccccccccccccccc
      SsssssssssssssSssSsssssssssssssS
      SssssssssssssssssssssssssssssssS
      SssssssssssssssssssssssssssssssS
      SssssssssssssssssssssssssssssssS
    `,
  },
  // Bloodrage Berserker: war-painted and roaring.
  card_w_berserker: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ...........b...bb...b...........
      .........b.bb.bbbb.bb.b....x....
      ....x...bbbbbbbbbbbbbbbb........
      .......bbbbbbbbbbbbbbbbbb.......
      ......bbbbbbbbbbbbbbbbbbbb..x...
      ...x..bbbbssssssssssssbbbb......
      ......bbbssssssssssssssbbb......
      ......bbsshhsssssssshhssbb...x..
      ..x...bbsxessssssssssexsbb......
      ......bbsxxssssSSssssxxsbb......
      ......bbsxsssssSSsssssxsbb......
      ......bbbsssswwwwwwssssbbb......
      ......bbbbssRRRRRRRRssbbbb......
      ......bbbbbsswwwwwwssbbbbb......
      .......bbbbbbbbbbbbbbbbbb.......
      ........bbbbbbbbbbbbbbbb........
      ...uuuuuubbbbbbbbbbbbbbuuuuuu...
      .uuuuuuuuubbbbbbbbbbbbuuuuuuuuu.
      uuUuuuuuuuubbbbssbbbbuuuuuuuuUuu
      uUuuuuuuuuussssssssssuuuuuuuuuUu
      uuuUuuuusssssSssssSsssssuuuuUuuu
      SssssssssssRssSssSsssssssssssssS
      SsssssSssRRssSssssSRsssssSsssssS
      SssssSssRssssSssssSsRsssssSssssS
      SsssSssssssssSssssSssRsssssSsssS
      SssssssssssssSSssSSsssRssssssssS
      SssssssssssssssssssssssRsssssssS
      SsssssssssssssSssSsssssssssssssS
      SssssssssssssssssssssssssssssssS
      SssssssssssssssssssssssssssssssS
      SssssssssssssssssssssssssssssssS
    `,
  },
  // Iron Resolve: a gleaming breastplate.
  card_w_resolve: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      ................................
      ................................
      ...llii..................iill...
      ..liiiiiI..............Iiiiiil..
      .liiiiiiiIIi........iIIiiiiiiil.
      .liiiiiiIliiiI....IiiilIiiiiiil.
      .liiiiiIliiiiiIIIIiiiiilIiiiiil.
      .IiiiiIliiiiiiilliiiiiiilIiyiiI.
      ..IIIIliiiiiiiilliiiiiiiilIyII..
      ....yIliiiiiiiilliiiiiiiiyywyy..
      ....yIliiiiiiiilliiiiiiiilIy....
      ..yywyyiiigiiiilliiiigiiilIy....
      ....yIliiiiiiiilliiiiiiiilI.....
      ....yIliiiiiiiilliiiiiiiilI.....
      ......IliiiiiiilliiiiiiilI......
      ......IliiiiiiilliiiiiiilI......
      ......gggggggggggggggggggg......
      ...y..IliiiiiiilliiiiiiilI..y...
      ..ywy.IlgiiiiiIllIiiiiiglI.ywy..
      ...y...IliiiiiilliiiiiilI...y...
      .......gggggggggggggggggg.......
      .......IliiiiiilliiiiiilI.......
      ......y.IliiiiilliiiiilI........
      .....ywyIIIIIIIIIIIIIIII.y......
      ......y.................ywy.....
      .........................y......
      ................................
      ................................
      ................................
      ................................
    `,
  },
  // Bastion Warden: great helm behind a tower shield.
  card_w_bastion: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      ................................
      ...........IIIIIIIIII...........
      .........IIiiiiiiiiiiII.........
      ........IiiiiilllliiiiiI........
      ........IiiiiiilliiiiiiI........
      ........IiiiiiIllIiiiiiI........
      ........IikkkkkkkkkkkkiI........
      ........IiiiiiikkiiiiiiI........
      ........IiiiiiikkiiiiiiI........
      ........IiiiiiiiiiiiiiiI........
      ........IIiiiiiiiiiiiiII........
      .........IIIIIIIIIIIIII.........
      ......rrrIIIIIIIIIIIIIIrrr......
      ...iiiiirrrrrrrrrrrrrrrriiiii...
      ..liiiiiirrrrrrrrrrrrrriiiiiil..
      .liiiiiiiiiiiiiiiiiiiiiiiIiiiil.
      .iiiiiillllllllllllllllllIiiiii.
      .iiiiiirgrrrrrrrrrrrrrrgrIiiiii.
      .iiiiiirrrrrrrrrrrrrrrrrrIiiiii.
      .iiiiiirRRRRRRRRRRRRRRRRrIiiiii.
      .iiiiiirrrrrrrGGGGrrrrrrrIiiiii.
      .iiiiiirrrrrrGgwggGrrrrrrIiiiii.
      .iiiiiirrrrrrGggggGrrrrrrIiiiii.
      .iiiiiirrrrrrGggggGrrrrrrIiiiii.
      .iiiiiirrrrrrGggggGrrrrrrIiiiii.
      .iiiiiirrrrrrrGGGGrrrrrrrIiiiii.
      .iiiiiirRRRRRRRRRRRRRRRRrIiiiii.
      .iiiiiirrrrrrrrrrrrrrrrrrIiiiii.
      .iiiiiirgrrrrrrrrrrrrrrgrIiiiii.
      .iiiiiirrrrrrrrrrrrrrrrrrIiiiii.
    `,
  },
  // Earthshatter: the ground splits and heaves.
  card_w_earthshatter: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      ................................
      ......................N......y..
      ............y........NnN........
      .......NNN..........NnnnN.......
      ......NnnnN..........NnN........
      ......NnnnN...........N.........
      ..y...NnnnN..............y......
      .......NNN....NnN..y............
      y.............nnn..........N....
      dyyy..........NnN.........NnN...
      dddNNNy...y..............NnnnN..
      dddNnNdyyy................NnN...
      dddNNNddddyyy..............N....
      dddddDdddddddyy.................
      dddddddddddddDd.................
      ddddddddddddddKKK...............
      ddddddDdddddddKKK...............
      ddddddddddddddKKK...............
      ddddddddddddDdKKK...............
      dddddddDddddddKKKyyyyyyy........
      dddddddddddddKKKKdddddddyyyyyyy.
      DddddddddddddKKKKKdddddDdddddddy
      ddddddddDddddKKKKKDddddddddddddD
      dddddddddddddKKKKKdddddddddddddd
      dDddddddddDddKKKKKddddddDddddddd
      dddddddddDddKKKKKKdddddddddddddd
      ddddddddddddKKKKKKdddddddddddddd
      ddDdddddddddKKKKKKKdDddddDdddddd
      ddddddddddDdKKKKKKKddddddddddddd
      ddddddddddddKKKKKKKddddddddddddd
    `,
  },
  // Iron Champion: horned great helm, spiked pauldrons, greatsword.
  card_w_champion: {
    palette,
    outline: OUTLINE,
    pixels: `
      ................................
      ................................
      .....w....................w.....
      .....ww..................wwi....
      ......ww...IIIIIIIIII...wwi.....
      ......wwwIIiiiiiiiiiiIIwwwI.....
      .......wwIiiiiiiiiiiiiIwwiI.....
      ........IiiiiiilliiiiiiIiI......
      ........IiiiiiilliiiiiiIII......
      ........IikkkkkkkkkkkkiII.......
      ........IiikxxkkkkxxkiiI........
      ........IiiiiiikkiiiiiiI........
      ........IiiiiiikkiiiiiiI........
      ........IIiiiiiiiiiiiiII........
      .........IIIIIIIIIIIIII.........
      ...w.....RrrrIIIIIIrrrR.....w...
      ..iwi..rrRrrrrrrrrrrrrRrr..iwi..
      .iiiii.rrrrrrrrrrrrrrrrrr.iiiii.
      iiiiiiiIiiiiiiiiiiiiiiiiIiiiiiii
      IiiiiiIiiiiiiiiiiiiiiiiiiIiiiiiI
      IIiiiIiiiiiiiigiigiiiiiiiiIiiiII
      rIIIIiiiiiiiiiiiiiiiiiiiiiiIIIIr
      rrRRRIiiiiiiigiiiigiiiiiiiIRRRrr
      rrrrRIiiiiiiiiiiiiiiiiiiiiIRrrrr
      rrrrRIiiiiiiigiiiigiiiiiiiIRrrrr
      rrrrRIiiiiiiiiiiiiiiiiiiiiIRrrrr
      rrrrRIIiiiiiiiiiiiiiiiiiiIIRrrrr
      rrrrRrIiiiiiigiiiigiiiiiiIrRrrrr
      rrrrRrIiiiiiiiiiiiiiiiiiiIrRrrrr
      rrrrRrIiiiiiiiiiiiiiiiiiiIrRrrrr
      rrrrRrIiiiiiigiiiigiiiiiiIrRrrrr
      rrrrRrIiiiiiiiiiiiiiiiiiiIrRrrrr
    `,
  },
};
